/* eslint-disable */
/**
 * IconSprite — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */

export default function IconSprite() {
  return (
    <>
      <svg width='0' height='0' style={{ position: 'absolute' }} aria-hidden='true' focusable='false'>
        <defs>
          <symbol id='i-arrow' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M7 17L17 7M9 7h8v8' />
          </symbol>
          <symbol id='i-arrow-r' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M4 12h15M13 6l6 6-6 6' />
          </symbol>
          <symbol id='i-chev' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M6 9l6 6 6-6' />
          </symbol>
          <symbol id='i-cal' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <rect x='3' y='5' width='18' height='16' rx='3' />
            <path d='M3 10h18M8 3v4M16 3v4' />
          </symbol>
          <symbol id='i-pin' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M12 21s7-6.2 7-11a7 7 0 10-14 0c0 4.8 7 11 7 11z' />
            <circle cx='12' cy='10' r='2.6' />
          </symbol>
          <symbol id='i-clock' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <circle cx='12' cy='12' r='9' />
            <path d='M12 7v5l3.5 2' />
          </symbol>
          <symbol id='i-users' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M16 20v-1.5a4 4 0 00-4-4H6a4 4 0 00-4 4V20' />
            <circle cx='9' cy='7' r='3.4' />
            <path d='M22 20v-1.5a4 4 0 00-3-3.87M16.5 3.7a4 4 0 010 6.6' />
          </symbol>
          <symbol id='i-search' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.9' strokeLinecap='round'>
            <circle cx='11' cy='11' r='7' />
            <path d='M20 20l-3.6-3.6' />
          </symbol>
          <symbol id='i-play' viewBox='0 0 24 24' fill='currentColor'>
            <path d='M8 5.6c0-.9 1-1.4 1.7-1L18.4 10c.7.4.7 1.5 0 1.9L9.7 17.3c-.7.4-1.7 0-1.7-1z' />
          </symbol>
          <symbol id='i-sun' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round'>
            <circle cx='12' cy='12' r='4.2' />
            <path d='M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4' />
          </symbol>
          <symbol id='i-moon' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M20 14.5A8.5 8.5 0 019.5 4a8.5 8.5 0 1010.5 10.5z' />
          </symbol>
          <symbol id='i-check' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2.4' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M20 6L9 17l-5-5' />
          </symbol>
          <symbol id='i-x' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round'>
            <path d='M6 6l12 12M18 6L6 18' />
          </symbol>
          <symbol id='i-in' viewBox='0 0 24 24' fill='currentColor'>
            <path d='M6.9 8.7H3.7V20h3.2zM5.3 3.6a1.9 1.9 0 100 3.8 1.9 1.9 0 000-3.8M20.3 20v-6.2c0-3.3-1.8-4.8-4.1-4.8-1.9 0-2.8 1-3.3 1.8V8.7H9.7V20H13v-6.2c0-1.5.9-2.3 2-2.3s1.9.7 1.9 2.3V20z' />
          </symbol>
          <symbol id='i-tw' viewBox='0 0 24 24' fill='currentColor'>
            <path d='M17.3 3h3.1l-6.8 7.8L21.7 21h-6.3l-4.9-6.4L4.8 21H1.7l7.3-8.3L1.6 3h6.4l4.5 5.9zm-1.1 16.1h1.7L7.9 4.8H6z' />
          </symbol>
          <symbol id='i-yt' viewBox='0 0 24 24' fill='currentColor'>
            <path d='M22.5 7.2a2.8 2.8 0 00-1.9-2C18.9 4.7 12 4.7 12 4.7s-6.9 0-8.6.5a2.8 2.8 0 00-1.9 2C1 8.9 1 12 1 12s0 3.1.5 4.8a2.8 2.8 0 001.9 2c1.7.5 8.6.5 8.6.5s6.9 0 8.6-.5a2.8 2.8 0 001.9-2c.5-1.7.5-4.8.5-4.8s0-3.1-.5-4.8M9.8 15.3V8.7l5.7 3.3z' />
          </symbol>
          <symbol id='i-dl' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M12 3v12M7.5 10.5L12 15l4.5-4.5M4 20h16' />
          </symbol>
          <symbol id='i-mail' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <rect x='2.5' y='4.5' width='19' height='15' rx='3' />
            <path d='M3 7l9 6 9-6' />
          </symbol>
          <symbol id='i-phone' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M21 16.9v2.6a1.9 1.9 0 01-2.1 1.9 18.9 18.9 0 01-8.2-2.9 18.6 18.6 0 01-5.7-5.7A18.9 18.9 0 012.1 4.6 1.9 1.9 0 014 2.5h2.6a1.9 1.9 0 011.9 1.6c.1 1 .3 1.9.7 2.8a1.9 1.9 0 01-.4 2L7.6 10a15 15 0 005.7 5.7l1.1-1.1a1.9 1.9 0 012-.4c.9.4 1.8.6 2.8.7a1.9 1.9 0 011.6 1.9z' />
          </symbol>
          <symbol id='i-ticket' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M3 9V7a2 2 0 012-2h14a2 2 0 012 2v2a3 3 0 000 6v2a2 2 0 01-2 2H5a2 2 0 01-2-2v-2a3 3 0 000-6z' />
            <path d='M14 5v14' strokeDasharray='2 2.6' />
          </symbol>
          <symbol id='i-mic' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <rect x='9' y='2.5' width='6' height='11' rx='3' />
            <path d='M5.5 11a6.5 6.5 0 0013 0M12 17.5V21M8.5 21h7' />
          </symbol>
          <symbol id='i-book' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M4 4.5A2.5 2.5 0 016.5 2H20v16H6.5A2.5 2.5 0 004 20.5z' />
            <path d='M4 18.5A2.5 2.5 0 016.5 16H20v6H6.5A2.5 2.5 0 014 19.5z' />
          </symbol>
          <symbol id='i-video' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <rect x='2.5' y='5.5' width='14' height='13' rx='3' />
            <path d='M16.5 10.5l5-3v9l-5-3z' />
          </symbol>
          <symbol id='i-grid' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7'>
            <rect x='3' y='3' width='7.5' height='7.5' rx='2' />
            <rect x='13.5' y='3' width='7.5' height='7.5' rx='2' />
            <rect x='3' y='13.5' width='7.5' height='7.5' rx='2' />
            <rect x='13.5' y='13.5' width='7.5' height='7.5' rx='2' />
          </symbol>
          <symbol id='i-spark' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M12 2.5l2.1 5.9 5.9 2.1-5.9 2.1L12 18.5l-2.1-5.9L4 10.5l5.9-2.1zM19 16l.9 2.6 2.6.9-2.6.9-.9 2.6-.9-2.6-2.6-.9 2.6-.9z' />
          </symbol>
          <symbol id='i-globe' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round'>
            <circle cx='12' cy='12' r='9' />
            <path d='M3 12h18M12 3a15 15 0 010 18 15 15 0 010-18' />
          </symbol>
          <symbol id='i-plus' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round'>
            <path d='M12 5v14M5 12h14' />
          </symbol>
          <symbol id='i-bookmark' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M6 3.5h12a1 1 0 011 1v16l-7-4.2-7 4.2v-16a1 1 0 011-1z' />
          </symbol>
          <symbol id='i-flag' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.7' strokeLinecap='round' strokeLinejoin='round'>
            <path d='M5 21V4M5 4h11l-1.6 3.6L16 11H5' />
          </symbol>
        </defs>
      </svg>
    </>
  );
}
