/* eslint-disable */
/**
 * SiteFooter — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import Link from 'next/link';

export default function SiteFooter() {
  return (
    <>
      <footer className='footer noise'>
        <div className='shell shell-wide relative'>
          <div className='footer__top'>
            <div>
              <Link className='brand' href='/' aria-label='Elets Events'>
                <img src='/assets/img/brand/logo.svg' alt='' width='34' height='34' />
                {' '}
                <span className='brand__name' style={{ color: '#fff' }}>
                  Elets
                  <span className='brand__sub'>
                    Events Platform
                  </span>
                </span>
              </Link>
              <p className='mt-5' style={{ color: 'rgba(255,255,255,.6)', maxWidth: '40ch' }}>
                {' '}India&apos;s leading B2B media house for governance, healthcare, education and banking. Founded 2003. Offices in Noida and Dubai.{' '}
              </p>
              <form className='newsletter' data-demo={"You're on the list — the next calendar drop is on its way."}>
                <label className='sr-only' htmlFor='nl'>
                  Email address
                </label>
                {' '}
                <input className='input' id='nl' name='email' type='email' required placeholder='you@organisation.gov.in' />
                {' '}
                <button className='btn btn-brand' type='submit'>
                  Subscribe
                </button>
              </form>
              <p className='mt-3' style={{ fontSize: '11px', color: 'rgba(255,255,255,.4)' }}>
                Monthly calendar drop. No sponsor mail. Unsubscribe anytime.
              </p>
            </div>
            <div className='footer__cols'>
              <div>
                <h4>
                  Events
                </h4>
                <ul>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      Upcoming conferences
                    </Link>
                  </li>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      Past conferences
                    </Link>
                  </li>
                  <li>
                    <Link href='/agenda'>
                      Agenda & tracks
                    </Link>
                  </li>
                  <li>
                    <Link href='/registration'>
                      Register
                    </Link>
                  </li>
                  <li>
                    <Link href='/registration#speaking'>
                      Speak at an event
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h4>
                  Media
                </h4>
                <ul>
                  <li>
                    <Link href='/videos'>
                      Video library
                    </Link>
                  </li>
                  <li>
                    <Link href='/magazines'>
                      eGov
                    </Link>
                  </li>
                  <li>
                    <Link href='/magazines'>
                      digitalLEARNING
                    </Link>
                  </li>
                  <li>
                    <Link href='/magazines'>
                      eHEALTH
                    </Link>
                  </li>
                  <li>
                    <Link href='/magazines'>
                      The Banking & Finance Post
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h4>
                  Company
                </h4>
                <ul>
                  <li>
                    <Link href='/about'>
                      About Elets
                    </Link>
                  </li>
                  <li>
                    <Link href='/sponsors'>
                      Partner with us
                    </Link>
                  </li>
                  <li>
                    <Link href='/gallery'>
                      Gallery
                    </Link>
                  </li>
                  <li>
                    <Link href='/news'>
                      Newsroom
                    </Link>
                  </li>
                  <li>
                    <Link href='/contact'>
                      Contact
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h4>
                  Next up
                </h4>
                <ul>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      India Energy Expo · 18–19 Aug
                    </Link>
                  </li>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      BFSI Gamechanger · Goa
                    </Link>
                  </li>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      World Education Summit · Delhi
                    </Link>
                  </li>
                  <li>
                    <Link href='/events/india-energy-expo-2026'>
                      Patient Centricity · Mumbai
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className='footer__offices'>
            <div className='office'>
              <h5>
                Noida — head office
              </h5>
              <p>
                Stellar IT Park, Sector 62
                <br />
                Noida, Uttar Pradesh 201309
                <br />
                India
              </p>
            </div>
            <div className='office'>
              <h5>
                Dubai
              </h5>
              <p>
                Elets Technomedia FZ-LLC
                <br />
                Dubai, United Arab Emirates
              </p>
            </div>
            <div className='office'>
              <h5>
                Secretariat
              </h5>
              <p>
                <a href='mailto:registration@eletsonline.com'>
                  registration@eletsonline.com
                </a>
                <br />
                {' '}
                <a href='mailto:partnerships@eletsonline.com'>
                  partnerships@eletsonline.com
                </a>
                <br />
                {' '}
                <a href='tel:+919289955093'>
                  +91 92899 55093
                </a>
              </p>
            </div>
          </div>
          <div className='footer__word' aria-hidden='true'>
            ELETS EVENTS
          </div>
          <div className='footer__bottom'>
            <span>
              ©{' '}
              <span data-year=''>
                2026
              </span>
              {' '}Elets Technomedia Pvt Ltd. All rights reserved.
            </span>
            <div className='socials'>
              <a href='#' aria-label='LinkedIn'>
                <svg width='15' height='15'>
                  <use href='#i-in' />
                </svg>
              </a>
              {' '}
              <a href='#' aria-label='X'>
                <svg width='14' height='14'>
                  <use href='#i-tw' />
                </svg>
              </a>
              {' '}
              <a href='#' aria-label='YouTube'>
                <svg width='16' height='16'>
                  <use href='#i-yt' />
                </svg>
              </a>
            </div>
            <span>
              Privacy · Terms · Code of conduct
            </span>
          </div>
        </div>
      </footer>
    </>
  );
}
