/* eslint-disable */
/**
 * VideoModal — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */

export default function VideoModal() {
  return (
    <>
      <div className='modal modal--video' id='video-modal' role='dialog' aria-modal='true' aria-label='Session video' aria-hidden='true'>
        <div className='modal__scrim'></div>
        <div className='modal__card'>
          <button className='modal__close' data-modal-close='' aria-label='Close video'>
            <svg width='15' height='15'>
              <use href='#i-x' />
            </svg>
          </button>
          <div className='ratio ratio-16-9' style={{ background: '#000' }}>
            <div style={{ display: 'grid', placeItems: 'center', height: '100%', color: 'rgba(255,255,255,.5)', textAlign: 'center', padding: '2rem' }}>
              <div>
                <svg width='38' height='38' aria-hidden='true'>
                  <use href='#i-play' />
                </svg>
                <p className='mono mt-4'>
                  Drop your player embed here
                </p>
                <p style={{ fontSize: 'var(--fs-xs)', maxWidth: '40ch', marginTop: '.5rem' }}>
                  {' '}{"Replace this block with a YouTube, Vimeo or self-hosted <video> element. The modal already pauses playback on close."}{' '}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
