/* eslint-disable */
/**
 * AboutBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function AboutBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li aria-current='page'>
                About
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            Twenty-three years of putting{' '}
            <em className='serif-i grad-text'>
              the right people
            </em>
            {' '}in one room
          </h1>
          <p className='lead'>
            {' '}Elets Technomedia was founded in 2003 to cover the technology that governments, hospitals, universities and banks were only beginning to adopt. The magazines came first. The conferences came because readers kept asking to meet each other.{' '}
          </p>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div className='grid g-4' data-reveal-group=''>
            <div className='stat' data-reveal='up'>
              <b data-count='1000' data-count-suf='+'>
                0
              </b>
              <span>
                Conferences convened
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='20000' data-count-suf='+'>
                0
              </b>
              <span>
                Speakers hosted
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='600000' data-count-suf='+'>
                0
              </b>
              <span>
                Delegates welcomed
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='475'>
                0
              </b>
              <span>
                Events in the archive
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='4' data-count-suf='M+'>
                0
              </b>
              <span>
                Monthly online readers
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='10' data-count-suf='M+'>
                0
              </b>
              <span>
                Session video views
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='4'>
                0
              </b>
              <span>
                Print & digital titles
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='2'>
                0
              </b>
              <span>
                Offices — Noida, Dubai
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell'>
          <div className='grid split' style={{ '--split': 'minmax(0,.85fr) minmax(0,1.15fr)', gap: 'clamp(2rem,5vw,5rem)', alignItems: 'start' } as CSSProperties}>
            <div>
              <span className='eyebrow'>
                How we work
              </span>
              <h2 className='h2 mt-5' data-split=''>
                The agenda is the product.
              </h2>
            </div>
            <div className='stack-lg' style={{ maxWidth: 'var(--maxw-prose)' }}>
              <p className='lead' style={{ color: 'var(--ink-2)' }}>
                {' '}Anyone can book a ballroom. What is difficult — and what takes two decades to build — is knowing which principal secretary is three months from a procurement decision, and which vendor has actually shipped the thing they are about to present.{' '}
              </p>
              <p className='muted'>
                {' '}Our programme committees are drawn from the editorial desks, not from sales. A session earns its slot because it answers a question the sector is currently stuck on. Sponsors get a speaking slot on the record; they do not get to write the agenda.{' '}
              </p>
              <p className='muted'>
                {' '}Government officers attend free at every Elets event. That is not generosity — it is the reason the rooms are worth attending. It also means the delegate mix skews toward people who sign off on things rather than people selling to them.{' '}
              </p>
              <div className='flex wrap gap-3 mt-4'>
                <Link className='btn btn-primary' href='/registration#speaking'>
                  Propose a session{' '}
                  <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </Link>
                {' '}
                <Link className='btn btn-ghost' href='/sponsors'>
                  Partnership principles
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='band-dark noise section'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Milestones
              </span>
              <h2 data-split=''>
                How it grew
              </h2>
            </div>
          </div>
          <div className='agenda' id='about-timeline'>
            <div className='agenda__progress' aria-hidden='true'></div>
            <article className='slot is-open track-gov'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='true'>
                <span className='slot__time'>
                  2003
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Elets Technomedia is founded in Noida
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Founding
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Founded by Dr Ravi Gupta, who remains CEO and Editor-in-Chief. The starting proposition: cover technology in the public sector properly, because nobody else was.
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-gov'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  2005–2010
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    eGov, digitalLEARNING and eHEALTH launch
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Publishing
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Three titles covering e-governance, education technology and health systems. Between them they still reach several million readers a month.
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-edu'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  2010s
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    The summit franchises take hold
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Events
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      The World Education Summit, Healthcare Innovation Summit and NBFC100 Tech Summit become annual fixtures — now in their 36th, 19th and 23rd editions respectively.
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-bfsi'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  2018
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    The Banking & Finance Post joins the stable
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Publishing
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Completing coverage across the four sectors where India&apos;s public and private institutions meet most often.
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-city'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  2020s
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Dubai office and international editions
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Expansion
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      A second office in Dubai, plus international editions of the education and health summits. Session video crosses ten million views.
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-ai'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  2026
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    India AI Summit named official pre-event to the India AI Impact Summit
                  </span>
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      AI
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Held 22 January at Eros Hotel, Nehru Place, New Delhi. 350 delegates, 60 speakers, 20 partners — and the AI programme now runs across every sector we cover.
                    </p>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Leadership
              </span>
              <h2 data-split=''>
                Who runs it
              </h2>
            </div>
          </div>
          <div className='grid split' style={{ '--split': 'minmax(0,.75fr) minmax(0,1.25fr)', gap: 'clamp(2rem,4vw,4rem)', alignItems: 'center' } as CSSProperties}>
            <div className='ratio ratio-3-4' style={{ borderRadius: 'var(--r-2xl)', overflow: 'hidden' }} data-reveal='scale'>
              <img src='/assets/img/speakers/sp-16.svg' alt='Dr Ravi Gupta' width='800' height='800' loading='lazy' decoding='async' />
            </div>
            <div>
              <h3 className='h3'>
                Dr Ravi Gupta
              </h3>
              <p className='mono muted mt-2'>
                Founder, Chief Executive Officer & Editor-in-Chief
              </p>
              <p className='lead mt-5'>
                {' '}Dr Gupta founded Elets in 2003 and still edits the flagship titles. He chairs the programme committees for the governance and AI franchises, and opens most national summits.{' '}
              </p>
              <div className='flex wrap gap-3 mt-6'>
                <a className='btn btn-soft' href='#' aria-label='LinkedIn'>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-in' />
                  </svg>
                  {' '}LinkedIn
                </a>
                {' '}
                <Link className='btn btn-soft' href='/speakers'>
                  Speaking history
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                The publishing arm
              </span>
              <h2 data-split=''>
                Four titles behind the conferences
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-soft' href='/magazines'>
                Magazine library{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-01.svg' alt='eGov' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <h3 className='mt-2'>
                  eGov
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-xs)' }}>
                  Governance & public sector technology
                </p>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-02.svg' alt='digitalLEARNING' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <h3 className='mt-2'>
                  digitalLEARNING
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-xs)' }}>
                  Education, skilling & employability
                </p>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-03.svg' alt='eHEALTH' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <h3 className='mt-2'>
                  eHEALTH
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-xs)' }}>
                  Hospitals, policy & medtech
                </p>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-04.svg' alt='The Banking & Finance Post' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <h3 className='mt-2'>
                  The Banking & Finance Post
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-xs)' }}>
                  Banking, NBFC, insurance & fintech
                </p>
              </div>
            </article>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell shell-wide'>
          <div className='grid split' style={{ '--split': 'minmax(0,1fr) minmax(0,1fr)', gap: 'clamp(2rem,4vw,3rem)', alignItems: 'center' } as CSSProperties}>
            <div className='map'>
              <div className='map__grid' aria-hidden='true'></div>
              <div className='pin'>
                <span className='pin__dot' aria-hidden='true'></span>
                {' '}
                <strong style={{ fontSize: 'var(--fs-sm)' }}>
                  Noida, Uttar Pradesh
                </strong>
                {' '}
                <span className='mono muted'>
                  Head office since 2003
                </span>
              </div>
            </div>
            <div className='stack'>
              <span className='eyebrow'>
                Where we are
              </span>
              <h2 className='h3'>
                Two offices, one secretariat
              </h2>
              <div className='grid g-2 mt-5'>
                <div className='card' style={{ padding: 'var(--sp-5)' }}>
                  <h3 className='h5'>
                    Noida — head office
                  </h3>
                  <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                    Stellar IT Park, Sector 62
                    <br />
                    Noida, Uttar Pradesh 201309
                    <br />
                    India
                  </p>
                </div>
                <div className='card' style={{ padding: 'var(--sp-5)' }}>
                  <h3 className='h5'>
                    Dubai
                  </h3>
                  <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                    Elets Technomedia FZ-LLC
                    <br />
                    Dubai
                    <br />
                    United Arab Emirates
                  </p>
                </div>
              </div>
              <Link className='btn btn-primary mt-5' href='/contact'>
                Get in touch{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                Work with us
              </span>
              <h2 className='mt-5' data-split=''>
                Three ways to be part of the next season.
              </h2>
              <p>
                Attend, speak, or partner. All three start with the same conversation.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg magnetic' href='/registration' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Register{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/registration#speaking'>
                  Speak
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/sponsors'>
                  Partner
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
