/* eslint-disable */
/**
 * AgendaBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function AgendaBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell shell-wide relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/events/india-energy-expo-2026'>
                  India Energy Expo 2026
                </Link>
              </li>
              <li aria-current='page'>
                Agenda
              </li>
            </ol>
          </nav>
          <div className='grid split' style={{ '--split': 'minmax(0,1.3fr) minmax(0,.7fr)', gap: 'clamp(2rem,4vw,4rem)', alignItems: 'end' } as CSSProperties}>
            <div>
              <h1 data-split=''>
                Two days, three tracks,{' '}
                <em className='serif-i grad-text'>
                  one calendar
                </em>
              </h1>
              <p className='lead'>
                {' '}Build your own day. Filter by track, search the session titles, and bookmark what matters — your selections are saved in this browser.{' '}
              </p>
            </div>
            <div className='kpi-strip' data-reveal='up'>
              <div className='kpi'>
                <b data-count='2'>
                  0
                </b>
                <span>
                  Days
                </span>
              </div>
              <div className='kpi'>
                <b data-count='3'>
                  0
                </b>
                <span>
                  Tracks
                </span>
              </div>
              <div className='kpi'>
                <b data-count='18'>
                  0
                </b>
                <span>
                  Sessions
                </span>
              </div>
              <div className='kpi'>
                <b data-count='60' data-count-suf='+'>
                  0
                </b>
                <span>
                  Speakers
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section-sm' style={{ paddingTop: 'var(--sp-5)' }}>
        <div className='shell shell-wide'>
          <div className='tabs' role='tablist' aria-label='Conference days'>
            <button role='tab' id='t-d1' aria-controls='p-d1' aria-selected='true'>
              Day one · Tue 18 Aug
            </button>
            {' '}
            <button role='tab' id='t-d2' aria-controls='p-d2' aria-selected='false' tabIndex={-1}>
              Day two · Wed 19 Aug
            </button>
            {' '}
            <button role='tab' id='t-saved' aria-controls='p-saved' aria-selected='false' tabIndex={-1}>
              My agenda
            </button>
          </div>
          <div className='grid mt-6 split' style={{ '--split': 'minmax(0,1fr) auto auto', gap: 'var(--sp-4)', alignItems: 'center' } as CSSProperties}>
            <div className='search'>
              <svg width='16' height='16' aria-hidden='true'>
                <use href='#i-search' />
              </svg>
              {' '}
              <label className='sr-only' htmlFor='ag-search'>
                Search sessions
              </label>
              {' '}
              <input className='input' id='ag-search' type='search' placeholder='Search sessions, speakers or rooms…' data-search='#day-one' />
            </div>
            <button className='btn btn-soft' data-expand-all='#day-one'>
              Expand all
            </button>
            {' '}
            <Link className='btn btn-primary' href='/registration'>
              Register{' '}
              <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
          <div className='filters mt-5' data-filters='#day-one' role='group' aria-label='Filter by track'>
            <span className='filters__pill' aria-hidden='true'></span>
            {' '}
            <button data-filter='all' aria-pressed='true'>
              All tracks
            </button>
            {' '}
            <button data-filter='plenary' aria-pressed='false'>
              Plenary
            </button>
            {' '}
            <button data-filter='grid' aria-pressed='false'>
              Grid & storage
            </button>
            {' '}
            <button data-filter='ai' aria-pressed='false'>
              AI & data
            </button>
            {' '}
            <button data-filter='policy' aria-pressed='false'>
              Policy & finance
            </button>
            {' '}
            <button data-filter='urban' aria-pressed='false'>
              Urban
            </button>
          </div>
          <div className='flex wrap gap-4 mt-5' aria-label='Track colour key'>
            <span className='tag tag-dot track-energy'>
              Plenary
            </span>
            {' '}
            <span className='tag tag-dot track-health'>
              Grid & storage
            </span>
            {' '}
            <span className='tag tag-dot track-ai'>
              AI & data
            </span>
            {' '}
            <span className='tag tag-dot track-gov'>
              Policy & finance
            </span>
            {' '}
            <span className='tag tag-dot track-city'>
              Urban
            </span>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div role='tabpanel' className='tabpanel' id='p-d1' aria-labelledby='t-d1'>
            <div className='agenda' id='day-one'>
              <div className='agenda__progress' aria-hidden='true'></div>
              <article className='slot is-open track-energy' data-cat='plenary' data-search-text='Registration coffee networking foyer'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='true'>
                  <span className='slot__time'>
                    08:30 — 09:30
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Registration, coffee and badge collection
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Plenary
                      </span>
                      <span className='tag'>
                        Foyer
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Badges are printed on arrival — bring photo ID. The exhibition floor opens at 08:45 and the delegate lounge stays open all day.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-energy' data-cat='plenary' data-search-text='Inaugural plenary grid 2035 Gaurav Gupta Ashok Meena main hall'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    09:30 — 10:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Inaugural plenary: the grid India will need in 2035
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Plenary
                      </span>
                      <span className='tag'>
                        Main hall
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Ministers, regulators and state utility chairs open the Expo with the demand picture to 2035 — and what has to be procured, financed and skilled before then.
                      </p>
                      <div className='slot__speakers'>
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-03.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Gaurav Gupta, IAS
                            </b>
                            <span>
                              Additional Chief Secretary, Energy, Government of Karnataka
                            </span>
                          </span>
                        </span>
                        {' '}
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-09.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Ashok K.K. Meena
                            </b>
                            <span>
                              Secretary, Ministry of Jal Shakti
                            </span>
                          </span>
                        </span>
                      </div>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s2' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-ai' data-cat='ai' data-search-text='Forecasting demand AI state utilities Shailesh Kumar Gaurav Duggal track A'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    10:30 — 11:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Forecasting demand with AI: what three state utilities learned
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        AI & data
                      </span>
                      <span className='tag'>
                        Track A
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        A working session on load forecasting models in production — data quality, procurement routes and the governance needed before a model touches dispatch.
                      </p>
                      <div className='slot__speakers'>
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-13.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Dr. Shailesh Kumar
                            </b>
                            <span>
                              Chief Data Scientist, CoE AI/ML, Jio
                            </span>
                          </span>
                        </span>
                        {' '}
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-14.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Gaurav Duggal
                            </b>
                            <span>
                              SVP & Head of Data Analytics & AI, Jio Platforms Limited
                            </span>
                          </span>
                        </span>
                      </div>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s3' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-health' data-cat='grid' data-search-text='Storage procurement battery pumped hydro tariff track B'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    10:30 — 11:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Storage procurement: batteries, pumped hydro and the tariff that makes either work
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Grid & storage
                      </span>
                      <span className='tag'>
                        Track B
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Parallel to the AI session. Procurement officers walk through two completed tenders line by line, including what they would write differently.
                      </p>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s4' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-gov' data-cat='policy' data-search-text='Public private partnership procurement clean energy Amit Sharma track B'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    11:30 — 12:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Public–private partnership: faster procurement for clean energy
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Policy & finance
                      </span>
                      <span className='tag'>
                        Track B
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Where PPP structures have unlocked capacity and where they have stalled, drawn from the PSU Summit&apos;s collaboration-for-innovation track.
                      </p>
                      <div className='slot__speakers'>
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-02.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Amit Sharma, IAS
                            </b>
                            <span>
                              Secretary & MD SIDCO, UT Administration Ladakh
                            </span>
                          </span>
                        </span>
                      </div>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s5' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-energy' data-cat='plenary' data-search-text='Lunch exhibition floor networking'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    12:30 — 14:00
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Lunch on the exhibition floor
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Plenary
                      </span>
                      <span className='tag'>
                        Expo hall
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Ninety minutes, deliberately. Most of the useful conversations at an Elets summit happen in this window rather than in the sessions.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-city' data-cat='urban' data-search-text='Urban energy cooling transport municipal balance sheet D Thara track A'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    14:00 — 14:45
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Urban energy: cooling, transport and the municipal balance sheet
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Urban
                      </span>
                      <span className='tag'>
                        Track A
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Municipal commissioners on the three line items that actually move a city&apos;s energy bill, and how they were financed.
                      </p>
                      <div className='slot__speakers'>
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-10.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              D Thara, IAS
                            </b>
                            <span>
                              Additional Secretary, Ministry of Housing and Urban Affairs
                            </span>
                          </span>
                        </span>
                      </div>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s7' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-gov' data-cat='policy' data-search-text='Green hydrogen offtake mission targets roundtable closed door'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    15:00 — 16:00
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Closed-door roundtable: green hydrogen, from target to signed offtake
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Policy & finance
                      </span>
                      <span className='tag'>
                        Boardroom
                      </span>
                      <span className='tag'>
                        Invitation only
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Twenty seats, Chatham House Rule, not recorded. Request an invitation through the secretariat when you register.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-energy' data-cat='plenary' data-search-text='Awards Energy Excellence dinner ballroom'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    19:00 — late
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Energy Excellence Awards & networking dinner
                    </span>
                    {' '}
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Plenary
                      </span>
                      <span className='tag'>
                        Ballroom
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Jury citations read from the stage, followed by dinner. Black tie is not expected; most of the room comes straight from the last session.
                      </p>
                      <button className='btn btn-soft btn-sm mt-5' data-bookmark='d1-s9' aria-pressed='false'>
                        <svg width='14' height='14' aria-hidden='true'>
                          <use href='#i-bookmark' />
                        </svg>
                        {' '}Add to my agenda
                      </button>
                    </div>
                  </div>
                </div>
              </article>
            </div>
            <p className='empty hide mt-6' data-empty=''>
              No sessions match those filters.
            </p>
          </div>
          <div role='tabpanel' className='tabpanel' id='p-d2' aria-labelledby='t-d2' hidden>
            <div className='agenda' id='day-two'>
              <div className='agenda__progress' aria-hidden='true'></div>
              <article className='slot is-open track-energy'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='true'>
                  <span className='slot__time'>
                    09:30 — 10:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Day two keynote: transmission, and the money that has to move first
                    </span>
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Plenary
                      </span>
                      <span className='tag'>
                        Main hall
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Evacuating renewables from where they are generated to where they are consumed — the single largest unfunded line in the transition.
                      </p>
                      <div className='slot__speakers'>
                        <span className='mini-speaker'>
                          <img src='/assets/img/speakers/sp-12.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                          <span>
                            <b>
                              Himanshu Pant
                            </b>
                            <span>
                              Chief Digital Officer, Adani Group
                            </span>
                          </span>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-ai'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    10:30 — 11:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Model governance: who signs off before an algorithm touches dispatch
                    </span>
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        AI & data
                      </span>
                      <span className='tag'>
                        Track A
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        A practical session on accountability structures, audit trails and the regulatory questions nobody has answered yet.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-health'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    11:30 — 12:15
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Skilling the sector: the workforce a rebuilt grid needs
                    </span>
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Grid & storage
                      </span>
                      <span className='tag'>
                        Track B
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Drawn from the National Skill & Education Summit programme — what the ITIs and polytechnics are actually producing, versus what utilities are hiring for.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article className='slot track-gov'>
                <span className='slot__dot' aria-hidden='true'></span>
                {' '}
                <button className='slot__head' aria-expanded='false'>
                  <span className='slot__time'>
                    14:00 — 15:00
                  </span>
                  {' '}
                  <span>
                    <span className='slot__title'>
                      Closing plenary: what we agreed, and what we did not
                    </span>
                    <span className='slot__tags'>
                      <span className='tag tag-dot'>
                        Policy & finance
                      </span>
                      <span className='tag'>
                        Main hall
                      </span>
                    </span>
                  </span>
                  {' '}
                  <span className='slot__toggle' aria-hidden='true'>
                    <svg width='13' height='13'>
                      <use href='#i-plus' />
                    </svg>
                  </span>
                </button>
                <div className='slot__panel'>
                  <div>
                    <div className='slot__body'>
                      <p>
                        Track chairs report back. The written summary is circulated to every delegate within a week, with dissent recorded rather than smoothed over.
                      </p>
                    </div>
                  </div>
                </div>
              </article>
            </div>
          </div>
          <div role='tabpanel' className='tabpanel' id='p-saved' aria-labelledby='t-saved' hidden>
            <div className='empty'>
              <svg width='26' height='26' style={{ marginInline: 'auto' }} aria-hidden='true'>
                <use href='#i-bookmark' />
              </svg>
              <p className='mt-4'>
                Sessions you bookmark appear here.
              </p>
              <p style={{ fontSize: 'var(--fs-xs)' }}>
                Open a session on Day one or Day two and choose “Add to my agenda”. Selections are stored in this browser only — nothing is sent to a server.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                Agenda closes six weeks out
              </span>
              <h2 className='mt-5' data-split=''>
                Want a session on this programme?
              </h2>
              <p>
                The committee reviews submissions fortnightly. Bring an argument and evidence; product pitches are declined.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg magnetic' href='/registration#speaking' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Submit a session{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/events/india-energy-expo-2026'>
                  Back to the event
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className='sticky-bar' data-sticky-bar='.page-head'>
        <div className='sticky-bar__inner'>
          <div className='sticky-bar__meta'>
            <strong style={{ fontSize: 'var(--fs-sm)' }}>
              India Energy Expo 2026 · Agenda
            </strong>
            {' '}
            <span className='mono muted' style={{ display: 'block' }}>
              18–19 August · New Delhi
            </span>
          </div>
          <div className='flex gap-2'>
            <Link className='btn btn-soft btn-sm' href='/events/india-energy-expo-2026'>
              Event
            </Link>
            {' '}
            <Link className='btn btn-primary btn-sm' href='/registration'>
              Register{' '}
              <svg className='btn__icon' width='13' height='13' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
