/* eslint-disable */
/**
 * ContactBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function ContactBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li aria-current='page'>
                Contact
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            Talk to the{' '}
            <em className='serif-i grad-text'>
              secretariat
            </em>
          </h1>
          <p className='lead'>
            {' '}One team handles delegates, speakers, partners and press. Pick the desk that fits and you will hear back within one working day.{' '}
          </p>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div className='grid g-4' data-reveal-group=''>
            <a className='card card--glow' href='#contact-form' data-reveal='up'>
              <div className='card__body'>
                <span className='mega__ico'>
                  <svg width='17' height='17' aria-hidden='true'>
                    <use href='#i-ticket' />
                  </svg>
                </span>
                <h3 className='h5 mt-3'>
                  Delegate registration
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Passes, government rates, group bookings and badge changes.
                </p>
                <p className='mt-auto' style={{ fontSize: 'var(--fs-sm)' }}>
                  <span className='link'>
                    registration@eletsonline.com
                  </span>
                  <br />
                  {' '}
                  <span className='mono muted'>
                    +91 92899 55093
                  </span>
                </p>
              </div>
            </a>
            {' '}
            <a className='card card--glow' href='#contact-form' data-reveal='up'>
              <div className='card__body'>
                <span className='mega__ico'>
                  <svg width='17' height='17' aria-hidden='true'>
                    <use href='#i-mic' />
                  </svg>
                </span>
                <h3 className='h5 mt-3'>
                  Speaking opportunities
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Session proposals, speaker nominations and programme queries.
                </p>
                <p className='mt-auto' style={{ fontSize: 'var(--fs-sm)' }}>
                  <span className='link'>
                    secretariat@eletsonline.com
                  </span>
                  <br />
                  {' '}
                  <span className='mono muted'>
                    +91 88606 51641
                  </span>
                </p>
              </div>
            </a>
            {' '}
            <Link className='card card--glow' href='/sponsors#enquire' data-reveal='up'>
              <div className='card__body'>
                <span className='mega__ico'>
                  <svg width='17' height='17' aria-hidden='true'>
                    <use href='#i-spark' />
                  </svg>
                </span>
                <h3 className='h5 mt-3'>
                  Partnerships
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Sponsorship tiers, exhibition stands and annual programmes.
                </p>
                <p className='mt-auto' style={{ fontSize: 'var(--fs-sm)' }}>
                  <span className='link'>
                    partnerships@eletsonline.com
                  </span>
                  <br />
                  {' '}
                  <span className='mono muted'>
                    Deck sent same day
                  </span>
                </p>
              </div>
            </Link>
            {' '}
            <a className='card card--glow' href='#contact-form' data-reveal='up'>
              <div className='card__body'>
                <span className='mega__ico'>
                  <svg width='17' height='17' aria-hidden='true'>
                    <use href='#i-book' />
                  </svg>
                </span>
                <h3 className='h5 mt-3'>
                  Press & media
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Accreditation, media kit, high-resolution imagery and interviews.
                </p>
                <p className='mt-auto' style={{ fontSize: 'var(--fs-sm)' }}>
                  <span className='link'>
                    press@eletsonline.com
                  </span>
                  <br />
                  {' '}
                  <span className='mono muted'>
                    Accreditation closes 7 days out
                  </span>
                </p>
              </div>
            </a>
          </div>
        </div>
      </section>
      <section className='section' id='contact-form' style={{ paddingTop: '0' }}>
        <div className='shell shell-wide'>
          <div className='grid split' style={{ '--split': 'minmax(0,1.25fr) minmax(0,.75fr)', gap: 'clamp(2rem,4vw,4rem)', alignItems: 'start' } as CSSProperties}>
            <div className='card' style={{ padding: 'clamp(1.5rem,3.5vw,3rem)' }}>
              <span className='eyebrow'>
                Send a message
              </span>
              <h2 className='h3 mt-4'>
                How can we help?
              </h2>
              <form className='mt-8' data-demo='Message received — the right desk will reply within one working day.'>
                <div className='field-row'>
                  <div className='field'>
                    <label htmlFor='c-name'>
                      Your name{' '}
                      <span className='req'>
                        *
                      </span>
                    </label>
                    <input className='input' id='c-name' name='name' required autoComplete='name' />
                  </div>
                  <div className='field'>
                    <label htmlFor='c-email'>
                      Email{' '}
                      <span className='req'>
                        *
                      </span>
                    </label>
                    <input className='input' id='c-email' name='email' type='email' required autoComplete='email' />
                  </div>
                </div>
                <div className='field-row mt-5'>
                  <div className='field'>
                    <label htmlFor='c-org'>
                      Organisation
                    </label>
                    <input className='input' id='c-org' name='org' autoComplete='organization' />
                  </div>
                  <div className='field'>
                    <label htmlFor='c-phone'>
                      Phone
                    </label>
                    <input className='input' id='c-phone' name='phone' type='tel' autoComplete='tel' />
                  </div>
                </div>
                <div className='field mt-5'>
                  <label htmlFor='c-topic'>
                    Which desk?{' '}
                    <span className='req'>
                      *
                    </span>
                  </label>
                  <select className='select' id='c-topic' name='topic' required>
                    <option value=''>
                      Choose one…
                    </option>
                    <option>
                      Delegate registration
                    </option>
                    <option>
                      Speaking opportunity
                    </option>
                    <option>
                      Sponsorship or exhibition
                    </option>
                    <option>
                      Press & media
                    </option>
                    <option>
                      Magazine subscription
                    </option>
                    <option>
                      Awards nomination
                    </option>
                    <option>
                      Something else
                    </option>
                  </select>
                </div>
                <div className='field mt-5'>
                  <label htmlFor='c-msg'>
                    Message{' '}
                    <span className='req'>
                      *
                    </span>
                  </label>
                  <textarea className='textarea' id='c-msg' name='message' required placeholder='Tell us what you need and which event it relates to.'></textarea>
                </div>
                <label className='check mt-5'>
                  <input type='checkbox' />
                  <span>
                    Also send me the monthly calendar drop. No sponsor mail.
                  </span>
                </label>
                {' '}
                <button className='btn btn-primary btn-lg mt-6' type='submit'>
                  Send message{' '}
                  <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </button>
                <p className='mono dim mt-4'>
                  We reply within one working day, Monday to Friday, 09:30–18:30 IST.
                </p>
              </form>
            </div>
            <aside className='side-sticky stack-lg'>
              <div className='map' style={{ aspectRatio: '4/3' }}>
                <div className='map__grid' aria-hidden='true'></div>
                <div className='pin'>
                  <span className='pin__dot' aria-hidden='true'></span>
                  {' '}
                  <strong style={{ fontSize: 'var(--fs-sm)' }}>
                    Noida — head office
                  </strong>
                  {' '}
                  <span className='mono muted'>
                    Sector 62
                  </span>
                </div>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Noida
                </h3>
                <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                  {' '}Elets Technomedia Pvt Ltd
                  <br />
                  {' '}Stellar IT Park, Sector 62
                  <br />
                  {' '}Noida, Uttar Pradesh 201309
                  <br />
                  {' '}India{' '}
                </p>
                <button className='btn btn-soft btn-sm mt-4' data-copy='Stellar IT Park, Sector 62, Noida, Uttar Pradesh 201309, India'>
                  Copy address
                </button>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Dubai
                </h3>
                <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                  {' '}Elets Technomedia FZ-LLC
                  <br />
                  {' '}Dubai
                  <br />
                  {' '}United Arab Emirates{' '}
                </p>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Follow
                </h3>
                <div className='flex gap-2 mt-4'>
                  <a className='icon-btn' href='#' aria-label='LinkedIn'>
                    <svg width='15' height='15'>
                      <use href='#i-in' />
                    </svg>
                  </a>
                  {' '}
                  <a className='icon-btn' href='#' aria-label='X'>
                    <svg width='14' height='14'>
                      <use href='#i-tw' />
                    </svg>
                  </a>
                  {' '}
                  <a className='icon-btn' href='#' aria-label='YouTube'>
                    <svg width='16' height='16'>
                      <use href='#i-yt' />
                    </svg>
                  </a>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell shell-narrow'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Quick answers
              </span>
              <h2 data-split=''>
                Before you write
              </h2>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Do government officers pay to attend?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  No. Serving officers of central and state government, PSUs and regulatory bodies attend every Elets event free of charge. Register with your official email address and the fee is waived automatically.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              How do I nominate a speaker?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Use the speaking submission form on the registration page, or write to the secretariat. Nominations are reviewed fortnightly by the programme committee; the agenda closes six weeks before each event.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Can I get the magazine in print?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Yes. Serving government officers and academic institutions receive the print edition free on request. Everyone else can read online free or take a paid print subscription.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              How do I get press accreditation?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Write to the press desk with your outlet and a recent byline. Accreditation closes seven days before each event; the media kit and high-resolution imagery are shared on approval.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Where do I send an awards nomination?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Through the form above, choosing "Awards nomination". Entries are assessed by an independent jury; Elets does not vote.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
