/* eslint-disable */
/**
 * EventBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs, then patched by it.
 * The event's identity (name, sector, dates, city, artwork, seat
 * allocation) comes from src/data/events.ts. The programme sections below —
 * tracks, venue notes, awards — remain the theme's illustrative copy for the
 * flagship edition.
 * Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';
import type { EventRecord } from '@/data/events';

export default function EventBody({ event }: { event: EventRecord }) {
  return (
    <>
      <section className='page-head noise' data-parallax-scope='' style={{ paddingBottom: '0' }}>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-wide relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/#events'>
                  Events
                </Link>
              </li>
              <li>
                <Link href='/events'>
                  {event.sectorLabel}
                </Link>
              </li>
              <li aria-current='page'>
                {event.name}
              </li>
            </ol>
          </nav>
          <div className='grid split' style={{ '--split': 'minmax(0,1.5fr) minmax(0,.85fr)', gap: 'clamp(2rem,4vw,4.5rem)', alignItems: 'start', marginTop: 'var(--sp-6)' } as CSSProperties}>
            <div>
              <div className='flex wrap gap-2'>
                <span className={event.status === 'open' ? 'tag tag-live' : 'tag'}>
                  {event.statusLabel ?? (event.status === 'concluded' ? 'Concluded' : 'Dates to be confirmed')}
                </span>
                {' '}
                <span className='tag tag-dot' style={{ '--dot': `var(--sector-${event.cats[0]})` } as CSSProperties}>
                  {event.sectorLabel}
                </span>
                {' '}
                <span className='tag'>
                  {event.dateLabel}
                </span>
              </div>
              <h1 className='mt-5' data-split=''>
                {event.name}
              </h1>
              <p className='lead'>
                {' '}{event.summary}{' '}
              </p>
              <div className='kpi-strip mt-8' data-reveal='up'>
                <div className='kpi'>
                  <b data-count='350' data-count-suf='+'>
                    0
                  </b>
                  <span>
                    Senior delegates
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='60' data-count-suf='+'>
                    0
                  </b>
                  <span>
                    Speakers on stage
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='20' data-count-suf='+'>
                    0
                  </b>
                  <span>
                    Partners & exhibitors
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='6' data-count-suf='+'>
                    0
                  </b>
                  <span>
                    Panel discussions
                  </span>
                </div>
              </div>
              <div className='mt-8' data-scale-in=''>
                <div className='ratio ratio-16-9' style={{ borderRadius: 'var(--r-2xl)', overflow: 'hidden' }}>
                  <img src='/assets/img/events/hero-wide.svg' alt={event.name} width='2400' height='1200' fetchPriority='high' decoding='async' />
                </div>
              </div>
            </div>
            <aside className='side-sticky' aria-label='Registration'>
              <div className='next-card' data-reveal='scale'>
                <span className='eyebrow'>
                  {event.startDate ? 'Doors open in' : 'On the calendar'}
                </span>
                {event.startDate ? (
                <div className='countdown' data-countdown={event.startDate} role='timer' aria-label={`Time until ${event.name}`}>
                  <div className='cd-unit'>
                    <b data-cd='d'>
                      00
                    </b>
                    <span>
                      Days
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='h'>
                      00
                    </b>
                    <span>
                      Hrs
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='m'>
                      00
                    </b>
                    <span>
                      Min
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='s'>
                      00
                    </b>
                    <span>
                      Sec
                    </span>
                  </div>
                </div>
                ) : (
                <p className='mono muted mt-3'>
                  {event.dateLabel}
                </p>
                )}
                <dl className='mt-5' style={{ display: 'grid', gap: '.85rem', fontSize: 'var(--fs-sm)' }}>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Dates
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        {event.dateLabel}
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Venue
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        {event.city ?? 'To be announced'}
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Format
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        Conference + Expo
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Language
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        English
                      </strong>
                    </dd>
                  </div>
                </dl>
                <div className='mt-5'>
                  <span className='seats__label'>
                    Delegate seats · {event.allocated}% allocated
                  </span>
                  {' '}
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar={String(event.allocated)}></span>
                  </span>
                </div>
                <Link className='btn btn-brand btn-lg btn-block mt-5 magnetic' href='/registration' data-magnet='0.18'>
                  <span className='magnetic__inner'>
                    Register now{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <a className='btn btn-soft btn-block mt-3' href='#brochure'>
                  Download brochure
                </a>
                <p className='mono dim text-center mt-4'>
                  Government officers attend free
                </p>
              </div>
            </aside>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell shell-wide'>
          <div className='tabs' role='tablist' aria-label='Event sections'>
            <button role='tab' id='t-about' aria-controls='p-about' aria-selected='true'>
              Overview
            </button>
            {' '}
            <button role='tab' id='t-themes' aria-controls='p-themes' aria-selected='false' tabIndex={-1}>
              Themes
            </button>
            {' '}
            <button role='tab' id='t-who' aria-controls='p-who' aria-selected='false' tabIndex={-1}>
              Who attends
            </button>
            {' '}
            <button role='tab' id='t-venue' aria-controls='p-venue' aria-selected='false' tabIndex={-1}>
              Venue & travel
            </button>
            {' '}
            <button role='tab' id='t-awards' aria-controls='p-awards' aria-selected='false' tabIndex={-1}>
              Awards
            </button>
          </div>
          <div className='mt-8'>
            <div role='tabpanel' className='tabpanel' id='p-about' aria-labelledby='t-about'>
              <div className='grid split' style={{ '--split': 'minmax(0,1.1fr) minmax(0,.9fr)', gap: 'clamp(2rem,4vw,4rem)' } as CSSProperties}>
                <div className='stack-lg'>
                  <p className='lead' style={{ color: 'var(--ink-2)' }}>
                    {' '}India&apos;s installed capacity has outrun the systems that plan for it. The Expo brings the three parties who have to reconcile that — central policy, state utilities and the technology vendors — into two days of working sessions rather than keynote theatre.{' '}
                  </p>
                  <p className='muted'>
                    {' '}Mornings are plenary: the demand picture, the financing picture, the regulatory calendar. Afternoons split into tracks, each closing with a written takeaway circulated to every delegate within a week. The exhibition floor runs throughout, and the Expo closes with the Energy Excellence Awards.{' '}
                  </p>
                  <p className='muted'>
                    {' '}As with every Elets summit, government officers attend at no cost. The delegate mix is deliberately weighted toward people who sign off on procurement.{' '}
                  </p>
                </div>
                <div>
                  <div className='grid g-2' data-reveal-group=''>
                    <div className='stat' data-reveal='up'>
                      <b>
                        2
                      </b>
                      <span>
                        Days of programming
                      </span>
                    </div>
                    <div className='stat' data-reveal='up'>
                      <b>
                        3
                      </b>
                      <span>
                        Parallel tracks
                      </span>
                    </div>
                    <div className='stat' data-reveal='up'>
                      <b>
                        1
                      </b>
                      <span>
                        Awards night
                      </span>
                    </div>
                    <div className='stat' data-reveal='up'>
                      <b>
                        24
                      </b>
                      <span>
                        Exhibition stands
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div role='tabpanel' className='tabpanel' id='p-themes' aria-labelledby='t-themes' hidden>
              <div className='grid g-3' data-reveal-group=''>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      01
                    </span>
                    <h3 className='h5'>
                      Grid & storage
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      Firming intermittent supply: battery procurement, pumped hydro and the tariff structures that make either viable.
                    </p>
                  </div>
                </div>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      02
                    </span>
                    <h3 className='h5'>
                      Green hydrogen
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      From mission targets to signed offtake: where the first Indian projects actually stand.
                    </p>
                  </div>
                </div>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      03
                    </span>
                    <h3 className='h5'>
                      AI in dispatch
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      Load forecasting in production — data quality, model governance and who is accountable when it is wrong.
                    </p>
                  </div>
                </div>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      04
                    </span>
                    <h3 className='h5'>
                      Transmission finance
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      Evacuating renewables from where they are generated to where they are consumed.
                    </p>
                  </div>
                </div>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      05
                    </span>
                    <h3 className='h5'>
                      Urban energy
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      Cooling, transport and the three line items that move a municipal energy bill.
                    </p>
                  </div>
                </div>
                <div className='card' data-reveal='up'>
                  <div className='card__body'>
                    <span className='mono muted'>
                      06
                    </span>
                    <h3 className='h5'>
                      Skilling the sector
                    </h3>
                    <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                      The workforce a rebuilt grid needs, and who is training it.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div role='tabpanel' className='tabpanel' id='p-who' aria-labelledby='t-who' hidden>
              <div className='grid g-2' style={{ gap: 'clamp(2rem,4vw,4rem)' }}>
                <div>
                  <h3 className='h4'>
                    Delegate profile
                  </h3>
                  <ul className='mt-5' style={{ display: 'grid', gap: '.9rem' }}>
                    <li className='flex gap-3'>
                      <svg width='17' height='17' style={{ color: 'var(--accent)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                      <span>
                        Principal secretaries and secretaries — Energy, Power, Urban Development
                      </span>
                    </li>
                    <li className='flex gap-3'>
                      <svg width='17' height='17' style={{ color: 'var(--accent)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                      <span>
                        Chairmen and MDs of state transmission and distribution utilities
                      </span>
                    </li>
                    <li className='flex gap-3'>
                      <svg width='17' height='17' style={{ color: 'var(--accent)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                      <span>
                        Regulatory commission members
                      </span>
                    </li>
                    <li className='flex gap-3'>
                      <svg width='17' height='17' style={{ color: 'var(--accent)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                      <span>
                        CTOs and heads of digital at IPPs and OEMs
                      </span>
                    </li>
                    <li className='flex gap-3'>
                      <svg width='17' height='17' style={{ color: 'var(--accent)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                      <span>
                        Infrastructure lenders and development finance institutions
                      </span>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className='h4'>
                    Split of the room
                  </h3>
                  <div className='mt-5' style={{ display: 'grid', gap: '1.35rem' }}>
                    <div>
                      <div className='flex between'>
                        <span style={{ fontSize: 'var(--fs-sm)' }}>
                          Government & PSU
                        </span>
                        <span className='mono muted'>
                          44%
                        </span>
                      </div>
                      <span className='seats__bar'>
                        <span className='seats__fill' data-bar='44'></span>
                      </span>
                    </div>
                    <div>
                      <div className='flex between'>
                        <span style={{ fontSize: 'var(--fs-sm)' }}>
                          Utilities & operators
                        </span>
                        <span className='mono muted'>
                          26%
                        </span>
                      </div>
                      <span className='seats__bar'>
                        <span className='seats__fill' data-bar='26'></span>
                      </span>
                    </div>
                    <div>
                      <div className='flex between'>
                        <span style={{ fontSize: 'var(--fs-sm)' }}>
                          Technology & OEM
                        </span>
                        <span className='mono muted'>
                          21%
                        </span>
                      </div>
                      <span className='seats__bar'>
                        <span className='seats__fill' data-bar='21'></span>
                      </span>
                    </div>
                    <div>
                      <div className='flex between'>
                        <span style={{ fontSize: 'var(--fs-sm)' }}>
                          Finance & advisory
                        </span>
                        <span className='mono muted'>
                          9%
                        </span>
                      </div>
                      <span className='seats__bar'>
                        <span className='seats__fill' data-bar='9'></span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div role='tabpanel' className='tabpanel' id='p-venue' aria-labelledby='t-venue' hidden>
              <div className='grid g-2' style={{ gap: 'clamp(2rem,4vw,3rem)', alignItems: 'start' }}>
                <div className='map'>
                  <div className='map__grid' aria-hidden='true'></div>
                  <div className='pin'>
                    <span className='pin__dot' aria-hidden='true'></span>
                    {' '}
                    <strong style={{ fontSize: 'var(--fs-sm)' }}>
                      New Delhi
                    </strong>
                    {' '}
                    <span className='mono muted'>
                      Venue confirmed closer to the date
                    </span>
                  </div>
                </div>
                <div className='stack'>
                  <h3 className='h4'>
                    Getting there
                  </h3>
                  <p className='muted'>
                    The Expo is held in central New Delhi, within 40 minutes of Indira Gandhi International Airport and walkable from the nearest Metro station. A shuttle runs between the partner hotels and the venue on both mornings.
                  </p>
                  <div className='grid g-2 mt-4'>
                    <div className='dl'>
                      <span className='dl__ico'>
                        <svg width='18' height='18' aria-hidden='true'>
                          <use href='#i-pin' />
                        </svg>
                      </span>
                      <span>
                        <b>
                          Venue map
                        </b>
                        <span>
                          PDF · 1.2 MB
                        </span>
                      </span>
                    </div>
                    <div className='dl'>
                      <span className='dl__ico'>
                        <svg width='18' height='18' aria-hidden='true'>
                          <use href='#i-ticket' />
                        </svg>
                      </span>
                      <span>
                        <b>
                          Hotel block rates
                        </b>
                        <span>
                          PDF · 480 KB
                        </span>
                      </span>
                    </div>
                  </div>
                  <p className='mono dim mt-4'>
                    Accessibility: step-free access throughout, reserved seating and a quiet room on both floors. Tell us what you need on the registration form.
                  </p>
                </div>
              </div>
            </div>
            <div role='tabpanel' className='tabpanel' id='p-awards' aria-labelledby='t-awards' hidden>
              <div className='grid split' style={{ '--split': 'minmax(0,1fr) minmax(0,1fr)', gap: 'clamp(2rem,4vw,4rem)' } as CSSProperties}>
                <div className='stack'>
                  <h3 className='h3'>
                    Energy Excellence Awards
                  </h3>
                  <p className='muted'>
                    Closing the second evening. Nominations are assessed by an independent jury of former regulators and sector academics; Elets has no vote.
                  </p>
                  <div className='flex wrap gap-3 mt-4'>
                    <Link className='btn btn-primary' href='/registration'>
                      Submit a nomination
                    </Link>
                    {' '}
                    <Link className='btn btn-ghost' href='/gallery'>
                      Last year&apos;s night
                    </Link>
                  </div>
                </div>
                <div className='grid g-2' data-reveal-group=''>
                  <div className='card' data-reveal='up'>
                    <div className='card__body'>
                      <h4 className='h5'>
                        Utility of the Year
                      </h4>
                      <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                        Distribution and transmission, judged separately.
                      </p>
                    </div>
                  </div>
                  <div className='card' data-reveal='up'>
                    <div className='card__body'>
                      <h4 className='h5'>
                        Grid Innovation
                      </h4>
                      <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                        Deployed, measured, in production.
                      </p>
                    </div>
                  </div>
                  <div className='card' data-reveal='up'>
                    <div className='card__body'>
                      <h4 className='h5'>
                        Green Hydrogen Project
                      </h4>
                      <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                        Signed offtake required.
                      </p>
                    </div>
                  </div>
                  <div className='card' data-reveal='up'>
                    <div className='card__body'>
                      <h4 className='h5'>
                        Public Sector Leader
                      </h4>
                      <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                        Individual award, jury nomination only.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='agenda'>
        <div className='shell'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Day one · 18 August
              </span>
              <h2 data-split=''>
                The programme
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-soft' href='/agenda'>
                Both days in full{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='agenda' id='event-agenda'>
            <div className='agenda__progress' aria-hidden='true'></div>
            <article className='slot is-open track-energy'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='true'>
                <span className='slot__time'>
                  09:30 — 10:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Inaugural plenary: the grid India will need in 2035
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Energy
                    </span>
                    <span className='tag'>
                      Main hall
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Ministers, regulators and state utility chairs open the Expo with the demand picture to 2035 — and what has to be procured, financed and skilled before then.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-03.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            Gaurav Gupta, IAS
                          </b>
                          <span>
                            Additional Chief Secretary, Energy, Government of Karnataka
                          </span>
                        </span>
                      </span>
                      {' '}
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-09.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            Ashok K.K. Meena
                          </b>
                          <span>
                            Secretary, Dept of Drinking Water & Sanitation, Ministry of Jal Shakti
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-ai'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  10:30 — 11:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Forecasting demand with AI: what three state utilities learned
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      AI
                    </span>
                    <span className='tag'>
                      Track A
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      A working session on load forecasting models in production — data quality, procurement routes and the governance needed before a model touches dispatch.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-13.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            Dr. Shailesh Kumar
                          </b>
                          <span>
                            Chief Data Scientist, CoE AI/ML, Jio
                          </span>
                        </span>
                      </span>
                      {' '}
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-14.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            Gaurav Duggal
                          </b>
                          <span>
                            SVP & Head of Data Analytics & AI, Jio Platforms Limited
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-gov'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  11:30 — 12:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Public–private partnership: faster procurement for clean energy
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Governance
                    </span>
                    <span className='tag'>
                      Track B
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Where PPP structures have unlocked capacity and where they have stalled — drawn from the PSU Summit&apos;s collaboration-for-innovation track.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-02.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            Amit Sharma, IAS
                          </b>
                          <span>
                            Secretary (IT, Transport, RD, S&T) & MD SIDCO, UT Administration Ladakh
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-city'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  14:00 — 14:45
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Urban energy: cooling, transport and the municipal balance sheet
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Smart Cities
                    </span>
                    <span className='tag'>
                      Track A
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Municipal commissioners on the three line items that actually move a city&apos;s energy bill, and how they were financed.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-10.svg' alt='' width='42' height='42' loading='lazy' decoding='async' />
                        <span>
                          <b>
                            D Thara, IAS
                          </b>
                          <span>
                            Additional Secretary, Ministry of Housing and Urban Affairs
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-energy'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  19:00 — late
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Energy Excellence Awards & networking dinner
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Awards
                    </span>
                    <span className='tag'>
                      Ballroom
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Jury citations read from the stage, followed by dinner. Black tie is not expected; most of the room comes straight from the last session.
                    </p>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
      <section className='section' id='speakers' data-rail=''>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Confirmed so far
              </span>
              <h2 data-split=''>
                Speakers
              </h2>
            </div>
            <div className='sec-head__aside flex gap-2'>
              <button className='icon-btn' data-rail-prev='' aria-label='Previous'>
                <svg width='16' height='16' style={{ transform: 'rotate(180deg)' }} aria-hidden='true'>
                  <use href='#i-arrow-r' />
                </svg>
              </button>
              {' '}
              <button className='icon-btn' data-rail-next='' aria-label='Next'>
                <svg width='16' height='16' aria-hidden='true'>
                  <use href='#i-arrow-r' />
                </svg>
              </button>
            </div>
          </div>
          <div className='speaker-rail' role='list'>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-03.svg' alt='Gaurav Gupta, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/gaurav-gupta' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/gaurav-gupta' data-cursor='Profile'>
                    Gaurav Gupta, IAS
                  </Link>
                </h3>
                <p>
                  Additional Chief Secretary, Energy, Government of Karnataka
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-09.svg' alt='Ashok K.K. Meena' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/ashok-k-k-meena' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/ashok-k-k-meena' data-cursor='Profile'>
                    Ashok K.K. Meena
                  </Link>
                </h3>
                <p>
                  Secretary, Dept of Drinking Water & Sanitation, Ministry of Jal Shakti
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-12.svg' alt='Himanshu Pant' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/himanshu-pant' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/himanshu-pant' data-cursor='Profile'>
                    Himanshu Pant
                  </Link>
                </h3>
                <p>
                  Chief Digital Officer, Adani Group
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-13.svg' alt='Dr. Shailesh Kumar' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/shailesh-kumar' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/shailesh-kumar' data-cursor='Profile'>
                    Dr. Shailesh Kumar
                  </Link>
                </h3>
                <p>
                  Chief Data Scientist, CoE AI/ML, Jio
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-10.svg' alt='D Thara, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/d-thara' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/d-thara' data-cursor='Profile'>
                    D Thara, IAS
                  </Link>
                </h3>
                <p>
                  Additional Secretary, Ministry of Housing and Urban Affairs
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-14.svg' alt='Gaurav Duggal' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/gaurav-duggal' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/gaurav-duggal' data-cursor='Profile'>
                    Gaurav Duggal
                  </Link>
                </h3>
                <p>
                  SVP & Head of Data Analytics & AI, Jio Platforms Limited
                </p>
              </div>
            </article>
          </div>
          <div className='text-center mt-6'>
            <Link className='btn btn-soft' href='/speakers'>
              All speakers{' '}
              <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
        </div>
      </section>
      <section className='band-dark noise section' id='sponsors'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Partners
              </span>
              <h2 data-split=''>
                Who is backing this edition
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-glass' href='/sponsors'>
                Partnership options{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='grid g-3 mb-8' data-reveal-group=''>
            <div className='card' style={{ background: 'transparent', borderColor: 'var(--line)' }} data-reveal='up'>
              <div className='card__body'>
                <span className='mono' style={{ color: 'var(--saffron-400)' }}>
                  Presenting partner
                </span>
                <img className='mt-4' src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' style={{ height: '36px', width: 'auto', filter: 'invert(1) hue-rotate(180deg)', opacity: '.9' }} loading='lazy' decoding='async' />
              </div>
            </div>
            <div className='card' style={{ background: 'transparent', borderColor: 'var(--line)' }} data-reveal='up'>
              <div className='card__body'>
                <span className='mono muted'>
                  Data streaming platform partner
                </span>
                <img className='mt-4' src='/assets/img/partners/p-02.svg' alt='Confluent' width='220' height='48' style={{ height: '36px', width: 'auto', filter: 'invert(1) hue-rotate(180deg)', opacity: '.9' }} loading='lazy' decoding='async' />
              </div>
            </div>
            <div className='card' style={{ background: 'transparent', borderColor: 'var(--line)' }} data-reveal='up'>
              <div className='card__body'>
                <span className='mono muted'>
                  Gold partner
                </span>
                <img className='mt-4' src='/assets/img/partners/p-03.svg' alt='Infinity Labs' width='220' height='48' style={{ height: '36px', width: 'auto', filter: 'invert(1) hue-rotate(180deg)', opacity: '.9' }} loading='lazy' decoding='async' />
              </div>
            </div>
          </div>
          <p className='mono muted mb-4'>
            Exhibitors
          </p>
          <div className='marquee' style={{ '--marquee-dur': '34s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-04.svg' alt='ESDS' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-05.svg' alt='Karix' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-06.svg' alt='Chat360' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-03.svg' alt='Infinity Labs' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='brochure'>
        <div className='shell shell-wide'>
          <div className='grid split' style={{ '--split': 'minmax(0,1.25fr) minmax(0,.75fr)', gap: 'clamp(2rem,4vw,4rem)', alignItems: 'start' } as CSSProperties}>
            <div>
              <div className='sec-head' style={{ marginBottom: 'var(--sp-6)' }}>
                <div>
                  <span className='sec-head__kicker mono'>
                    From the last edition
                  </span>
                  <h2 className='h3'>
                    Watch & browse
                  </h2>
                </div>
              </div>
              <a className='video video--hero mb-5' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
                <img src='/assets/img/videos/vid-07.svg' alt='Energy transition keynote' width='1600' height='900' loading='lazy' decoding='async' />
                {' '}
                <span className='video__dur'>
                  36:58
                </span>
                {' '}
                <span className='video__play'>
                  <i>
                    <svg width='20' height='20' aria-hidden='true'>
                      <use href='#i-play' />
                    </svg>
                  </i>
                </span>
                {' '}
                <span className='video__meta'>
                  <h3 style={{ fontSize: 'var(--fs-md)' }}>
                    The energy transition, financed
                  </h3>
                  <p>
                    India Energy Expo · preview session
                  </p>
                </span>
              </a>
              <div className='grid g-3' data-reveal-group=''>
                <Link className='masonry-item' href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
                  <img src='/assets/img/gallery/g-03.svg' alt='Expo floor' width='1200' height='900' loading='lazy' decoding='async' />
                </Link>
                {' '}
                <Link className='masonry-item' href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
                  <img src='/assets/img/gallery/g-05.svg' alt='Fireside chat' width='1200' height='900' loading='lazy' decoding='async' />
                </Link>
                {' '}
                <Link className='masonry-item' href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
                  <img src='/assets/img/gallery/g-08.svg' alt='Awards night' width='1200' height='900' loading='lazy' decoding='async' />
                </Link>
              </div>
            </div>
            <div className='stack'>
              <h3 className='h4'>
                Downloads
              </h3>
              <a className='dl' href='#brochure'>
                <span className='dl__ico'>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-dl' />
                  </svg>
                </span>
                <span>
                  <b>
                    Delegate brochure
                  </b>
                  <span>
                    PDF · 3.4 MB
                  </span>
                </span>
              </a>
              {' '}
              <a className='dl' href='#brochure'>
                <span className='dl__ico'>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-dl' />
                  </svg>
                </span>
                <span>
                  <b>
                    Sponsorship deck
                  </b>
                  <span>
                    PDF · 5.1 MB
                  </span>
                </span>
              </a>
              {' '}
              <a className='dl' href='#brochure'>
                <span className='dl__ico'>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-dl' />
                  </svg>
                </span>
                <span>
                  <b>
                    Floor plan & stands
                  </b>
                  <span>
                    PDF · 900 KB
                  </span>
                </span>
              </a>
              {' '}
              <Link className='dl' href='/agenda'>
                <span className='dl__ico'>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-cal' />
                  </svg>
                </span>
                <span>
                  <b>
                    Agenda (both days)
                  </b>
                  <span>
                    PDF · 620 KB
                  </span>
                </span>
              </Link>
              <h3 className='h4 mt-6'>
                Secretariat
              </h3>
              <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                {' '}Delegate registration
                <br />
                {' '}
                <a className='link' href='mailto:registration@eletsonline.com'>
                  registration@eletsonline.com
                </a>
                <br />
                <br />
                {' '}Speaking opportunities
                <br />
                {' '}
                <a className='link' href='mailto:secretariat@eletsonline.com'>
                  secretariat@eletsonline.com
                </a>
                <br />
                <br />
                {' '}Partnerships
                <br />
                {' '}
                <a className='link' href='mailto:partnerships@eletsonline.com'>
                  partnerships@eletsonline.com
                </a>
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell shell-narrow'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Before you register
              </span>
              <h2 data-split=''>
                Frequently asked
              </h2>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Is there a charge for government officers?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  No. Serving officers of central and state government, PSUs and regulatory bodies attend free of charge. Register with your official email address and the fee is waived automatically.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Can I send a colleague in my place?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Yes, up to 48 hours before the first session. Email the secretariat with the replacement delegate&apos;s details and we will reissue the badge.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Are the sessions recorded?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Plenaries and most track sessions are recorded and published to the video library within three weeks. Closed-door roundtables are not recorded and operate under the Chatham House Rule.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              How do I propose a session or a speaker?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Use the speaking submission form on the registration page. The programme committee reviews submissions fortnightly and the agenda closes six weeks before the event.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              What does a partnership include?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Packages range from an exhibition stand to a presenting partnership with a keynote slot and branding across the magazine and video library. The sponsors page has the full grid, or ask for the deck.
                </p>
              </div>
            </div>
          </div>
          <div className='acc'>
            <button className='acc__btn' aria-expanded='false'>
              Is there a hotel block?
              <span className='acc__ico' aria-hidden='true'></span>
            </button>
            <div className='acc__panel'>
              <div>
                <p>
                  Yes, at three partner hotels within a short drive of the venue. Rates and the booking code are on the registration form under Accommodation.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                {[event.dateLabel, event.city].filter(Boolean).join(' · ')}
              </span>
              <h2 className='mt-5' data-split=''>
                Seats are allocated, not sold.
              </h2>
              <p>
                We cap the room so the conversations stay useful. Register early and tell us which sessions matter to you.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg magnetic' href='/registration' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Register as delegate{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/sponsors'>
                  Partner with the Expo
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className='sticky-bar' data-sticky-bar='.page-head'>
        <div className='sticky-bar__inner'>
          <div className='sticky-bar__meta'>
            <strong style={{ fontSize: 'var(--fs-sm)' }}>
              {event.name}
            </strong>
            {' '}
            <span className='mono muted' style={{ display: 'block' }}>
              {[event.dateLabel, event.city, `${event.allocated}% allocated`].filter(Boolean).join(' · ')}
            </span>
          </div>
          <div className='flex gap-2'>
            <Link className='btn btn-soft btn-sm' href='/agenda'>
              Agenda
            </Link>
            {' '}
            <Link className='btn btn-primary btn-sm' href='/registration'>
              Register{' '}
              <svg className='btn__icon' width='13' height='13' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
        </div>
      </div>
      <div className='modal modal--video' id='video-modal' role='dialog' aria-modal='true' aria-label='Session video' aria-hidden='true'>
        <div className='modal__scrim'></div>
        <div className='modal__card'>
          <button className='modal__close' data-modal-close='' aria-label='Close video'>
            <svg width='15' height='15'>
              <use href='#i-x' />
            </svg>
          </button>
          <div className='ratio ratio-16-9' style={{ background: '#000' }}>
            <div style={{ display: 'grid', placeItems: 'center', height: '100%', color: 'rgba(255,255,255,.5)', textAlign: 'center', padding: '2rem' }}>
              <div>
                <svg width='38' height='38' aria-hidden='true'>
                  <use href='#i-play' />
                </svg>
                <p className='mono mt-4'>
                  Drop your player embed here
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
