/* eslint-disable */
/**
 * GalleryBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import Link from 'next/link';

export default function GalleryBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                Media
              </li>
              <li aria-current='page'>
                Gallery
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            What the room{' '}
            <em className='serif-i grad-text'>
              actually looks like
            </em>
          </h1>
          <p className='lead'>
            Photography from recent Elets summits, awards nights and expo floors — plenaries, roundtables, and the corridor conversations that follow them.
          </p>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div className='filters mb-8' data-filters='#gallery-grid' role='group' aria-label='Filter photographs by event'>
            <span className='filters__pill' aria-hidden='true'></span>
            {' '}
            <button data-filter='all' aria-pressed='true'>
              All events
            </button>
            {' '}
            <button data-filter='ai' aria-pressed='false'>
              AI
            </button>
            {' '}
            <button data-filter='gov' aria-pressed='false'>
              Governance
            </button>
            {' '}
            <button data-filter='health' aria-pressed='false'>
              Healthcare
            </button>
            {' '}
            <button data-filter='edu' aria-pressed='false'>
              Education
            </button>
            {' '}
            <button data-filter='bfsi' aria-pressed='false'>
              Banking
            </button>
            {' '}
            <button data-filter='city' aria-pressed='false'>
              Smart Cities
            </button>
            {' '}
            <button data-filter='energy' aria-pressed='false'>
              Energy
            </button>
          </div>
          <div className='masonry' id='gallery-grid' data-reveal-group='' aria-live='polite'>
            <figure data-cat='ai' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Plenary hall — India AI Summit 2026'>
                <img src='/assets/img/gallery/g-01.svg' alt='Plenary hall at India AI Summit 2026' width='1200' height='1500' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Plenary hall
                </strong>
                <br />
                <span className='dim'>
                  India AI Summit 2026
                </span>
              </figcaption>
            </figure>
            <figure data-cat='health' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Awards night — Healthcare Innovation Summit'>
                <img src='/assets/img/gallery/g-02.svg' alt='Awards night at Healthcare Innovation Summit' width='1200' height='800' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Awards night
                </strong>
                <br />
                <span className='dim'>
                  Healthcare Innovation Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='energy' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Expo floor — India Energy Expo'>
                <img src='/assets/img/gallery/g-03.svg' alt='Expo floor at India Energy Expo' width='1200' height='1350' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Expo floor
                </strong>
                <br />
                <span className='dim'>
                  India Energy Expo
                </span>
              </figcaption>
            </figure>
            <figure data-cat='gov' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Roundtable — National PSU Summit'>
                <img src='/assets/img/gallery/g-04.svg' alt='Roundtable at National PSU Summit' width='1200' height='900' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Roundtable
                </strong>
                <br />
                <span className='dim'>
                  National PSU Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='bfsi' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Fireside chat — World Fintech Summit'>
                <img src='/assets/img/gallery/g-05.svg' alt='Fireside chat at World Fintech Summit' width='1200' height='1200' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Fireside chat
                </strong>
                <br />
                <span className='dim'>
                  World Fintech Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='edu' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Networking break — Campus to Career'>
                <img src='/assets/img/gallery/g-06.svg' alt='Networking break at Campus to Career' width='1200' height='900' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Networking break
                </strong>
                <br />
                <span className='dim'>
                  Campus to Career
                </span>
              </figcaption>
            </figure>
            <figure data-cat='city' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Panel discussion — Urban Innovation Summit'>
                <img src='/assets/img/gallery/g-07.svg' alt='Panel discussion at Urban Innovation Summit' width='1200' height='1500' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Panel discussion
                </strong>
                <br />
                <span className='dim'>
                  Urban Innovation Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='gov' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Keynote — Digital Innovation Summit'>
                <img src='/assets/img/gallery/g-08.svg' alt='Keynote at Digital Innovation Summit' width='1200' height='800' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Keynote
                </strong>
                <br />
                <span className='dim'>
                  Digital Innovation Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='bfsi' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Registration desk — NBFC100 Tech Summit'>
                <img src='/assets/img/gallery/g-09.svg' alt='Registration desk at NBFC100 Tech Summit' width='1200' height='1350' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Registration desk
                </strong>
                <br />
                <span className='dim'>
                  NBFC100 Tech Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='health' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Award citation — Patient Centricity Summit'>
                <img src='/assets/img/gallery/g-10.svg' alt='Award citation at Patient Centricity Summit' width='1200' height='900' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Award citation
                </strong>
                <br />
                <span className='dim'>
                  Patient Centricity Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='edu' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Delegate lounge — World Education Summit'>
                <img src='/assets/img/gallery/g-11.svg' alt='Delegate lounge at World Education Summit' width='1200' height='1200' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Delegate lounge
                </strong>
                <br />
                <span className='dim'>
                  World Education Summit
                </span>
              </figcaption>
            </figure>
            <figure data-cat='ai' data-reveal='up'>
              <a href='#gal-modal' data-modal-open='gal-modal' data-cursor='View' aria-label='Closing plenary — AI Summit on Water'>
                <img src='/assets/img/gallery/g-12.svg' alt='Closing plenary at AI Summit on Water' width='1200' height='900' loading='lazy' decoding='async' />
              </a>
              <figcaption>
                <strong>
                  Closing plenary
                </strong>
                <br />
                <span className='dim'>
                  AI Summit on Water
                </span>
              </figcaption>
            </figure>
          </div>
          <p className='empty hide mt-6' data-empty=''>
            No photographs from that event yet.
          </p>
          <div className='text-center mt-9'>
            <a className='btn btn-ghost btn-lg magnetic' href='#' data-magnet='0.2'>
              <span className='magnetic__inner'>
                Load more photographs
              </span>
            </a>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                Press & media
              </span>
              <h2 className='mt-5' data-split=''>
                Need high-resolution files?
              </h2>
              <p>
                Accredited press can request originals, speaker headshots and the event media kit from the communications desk.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg' href='/contact'>
                  Request media kit{' '}
                  <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/videos'>
                  Watch the sessions
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className='modal' id='gal-modal' role='dialog' aria-modal='true' aria-label='Photograph' aria-hidden='true'>
        <div className='modal__scrim'></div>
        <div className='modal__card' style={{ padding: '0', overflow: 'hidden' }}>
          <button className='modal__close' data-modal-close='' aria-label='Close'>
            <svg width='15' height='15'>
              <use href='#i-x' />
            </svg>
          </button>
          {' '}
          <img src='/assets/img/gallery/g-01.svg' alt='Plenary hall' width='1200' height='1500' style={{ width: '100%', height: 'auto' }} />
          <div style={{ padding: 'var(--sp-5)' }}>
            <strong>
              Plenary hall
            </strong>
            <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
              India AI Summit 2026 · Eros Hotel, Nehru Place, New Delhi
            </p>
            <p className='mono dim mt-3'>
              Wire this modal to your lightbox of choice, or swap the src on open.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
