/* eslint-disable */
/**
 * HomeBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function HomeBody() {
  return (
    <>
      <section className='hero noise' data-parallax-scope=''>
        <canvas className='hero__canvas' aria-hidden='true'></canvas>
        <div className='grid-lines hero__grid' aria-hidden='true'></div>
        <div className='relative' data-particles='16' style={{ position: 'absolute', inset: '0', color: 'var(--accent)', pointerEvents: 'none' }} aria-hidden='true'></div>
        <div className='hero__inner'>
          <div className='shell shell-wide'>
            <div className='hero__layout'>
              <div>
                <span className='tag tag-live' data-hero-in='' data-reveal='up'>
                  Registrations open · India Energy Expo, 18–19 Aug
                </span>
                <h1 className='mt-5' data-split=''>
                  {' '}India&apos;s biggest ideas
                  <br />
                  {' '}get their{' '}
                  <em className='serif-i grad-text'>
                    first hearing
                  </em>
                  <br />
                  {' '}on our stage.{' '}
                </h1>
                <p className='hero__sub' data-hero-in='' data-reveal='up'>
                  {' '}Elets Technomedia has convened the country&apos;s policymakers, hospital chiefs, vice-chancellors, bankers and technologists since 2003 — across governance, healthcare, education, BFSI, AI, urban and energy.{' '}
                </p>
                <div className='hero__cta' data-hero-in='' data-reveal='up'>
                  <Link className='btn btn-primary btn-lg magnetic' href='/registration' data-magnet='0.2'>
                    <span className='magnetic__inner'>
                      Register as delegate{' '}
                      <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </span>
                  </Link>
                  {' '}
                  <a className='btn btn-ghost btn-lg' href='#events'>
                    Browse 2026 calendar
                  </a>
                </div>
                <div className='hero__stats' data-reveal-group=''>
                  <div className='hero__stat' data-reveal='up'>
                    <span className='n' data-count='1000' data-count-suf='+'>
                      0
                    </span>
                    <span className='l'>
                      Conferences convened since 2003
                    </span>
                  </div>
                  <div className='hero__stat' data-reveal='up'>
                    <span className='n' data-count='20000' data-count-suf='+'>
                      0
                    </span>
                    <span className='l'>
                      Speakers hosted on our stages
                    </span>
                  </div>
                  <div className='hero__stat' data-reveal='up'>
                    <span className='n' data-count='600000' data-count-suf='+'>
                      0
                    </span>
                    <span className='l'>
                      Delegates through the doors
                    </span>
                  </div>
                  <div className='hero__stat' data-reveal='up'>
                    <span className='n' data-count='28' data-count-suf=' states'>
                      0
                    </span>
                    <span className='l'>
                      Plus international editions
                    </span>
                  </div>
                </div>
              </div>
              <aside className='next-card float' data-hero-in='' data-reveal='scale' aria-labelledby='next-h'>
                <div className='next-card__media'>
                  <img src='/assets/img/events/ev-01.svg' alt='India Energy Expo 2026' width='1600' height='1000' fetchPriority='high' decoding='async' />
                </div>
                <span className='eyebrow'>
                  Next on the calendar
                </span>
                <h3 id='next-h' className='mt-3'>
                  India Energy Expo 2026
                </h3>
                <div className='next-card__meta'>
                  <span>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}18–19 August 2026
                  </span>
                  {' '}
                  <span>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}New Delhi
                  </span>
                </div>
                <div className='countdown' data-countdown='2026-08-18T09:30:00+05:30' role='timer' aria-label='Time until India Energy Expo 2026'>
                  <div className='cd-unit'>
                    <b data-cd='d'>
                      00
                    </b>
                    <span>
                      Days
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='h'>
                      00
                    </b>
                    <span>
                      Hrs
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='m'>
                      00
                    </b>
                    <span>
                      Min
                    </span>
                  </div>
                  <div className='cd-unit'>
                    <b data-cd='s'>
                      00
                    </b>
                    <span>
                      Sec
                    </span>
                  </div>
                </div>
                <div className='flex gap-2 mt-5'>
                  <Link className='btn btn-brand btn-sm' style={{ flex: '1' }} href='/events/india-energy-expo-2026'>
                    Event details
                  </Link>
                  {' '}
                  <Link className='btn btn-soft btn-sm' style={{ flex: '1' }} href='/agenda'>
                    Agenda
                  </Link>
                </div>
              </aside>
            </div>
            <div className='flex center gap-4 mt-9' data-reveal='up'>
              <span className='scroll-hint' aria-hidden='true'></span>
              {' '}
              <span className='mono muted'>
                Scroll to explore the 2026 calendar
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section-tight' aria-label='Institutions represented'>
        <div className='shell shell-wide'>
          <p className='mono muted text-center mb-6'>
            Leaders from these institutions have spoken at Elets summits
          </p>
          <div className='marquee' style={{ '--marquee-dur': '52s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-07.svg' alt='Digital India' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-11.svg' alt='MeitY' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-10.svg' alt='NITI Aayog' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-08.svg' alt='MyGov' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-09.svg' alt='ONDC' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-12.svg' alt='FSSAI' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-02.svg' alt='Confluent' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-04.svg' alt='ESDS' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell'>
          <div className='grid split' style={{ '--split': 'minmax(0,1fr) minmax(0,1.15fr)', gap: 'clamp(2rem,5vw,6rem)', alignItems: 'start' } as CSSProperties}>
            <div>
              <span className='eyebrow' data-reveal='up'>
                Why it matters
              </span>
              <h2 className='h2 mt-5' data-split=''>
                {' '}A conference is only as good as the{' '}
                <em className='serif-i'>
                  decisions
                </em>
                {' '}it makes possible.{' '}
              </h2>
              <div className='flex wrap gap-3 mt-8' data-reveal='up'>
                <Link className='btn btn-primary' href='/about'>
                  How we build an agenda{' '}
                  <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </Link>
                {' '}
                <Link className='btn btn-ghost' href='/registration#speaking'>
                  Propose a session
                </Link>
              </div>
            </div>
            <div className='stack-lg'>
              <p className='lead' data-reveal='up'>
                {' '}Elets does not run trade shows. We build rooms where a principal secretary, a hospital CIO and a platform architect end up at the same table — and leave with something to act on. Twenty-three years of that has produced a network no other B2B media house in India can convene at short notice.{' '}
              </p>
              <div className='grid g-2' data-reveal-group=''>
                <div className='stat' data-reveal='up'>
                  <b data-count='475'>
                    0
                  </b>
                  <span>
                    Events archived and searchable on this platform
                  </span>
                </div>
                <div className='stat' data-reveal='up'>
                  <b data-count='4' data-count-suf='M+'>
                    0
                  </b>
                  <span>
                    Monthly readers across our four magazines
                  </span>
                </div>
                <div className='stat' data-reveal='up'>
                  <b data-count='10' data-count-suf='M+'>
                    0
                  </b>
                  <span>
                    Views on session video published to date
                  </span>
                </div>
                <div className='stat' data-reveal='up'>
                  <b data-count='2003' data-count-plain=''>
                    0
                  </b>
                  <span>
                    Founded in Noida; second office in Dubai
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='events'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                The 2026–27 calendar
              </span>
              <h2 data-split=''>
                Where India&apos;s sectors meet next
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='link' href='/events/india-energy-expo-2026'>
                All 475 events in the archive{' '}
                <svg width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='filters mb-8' data-filters='#event-grid' role='group' aria-label='Filter events by sector'>
            <span className='filters__pill' aria-hidden='true'></span>
            {' '}
            <button data-filter='all' aria-pressed='true'>
              All sectors
            </button>
            {' '}
            <button data-filter='ai' aria-pressed='false'>
              AI
            </button>
            {' '}
            <button data-filter='health' aria-pressed='false'>
              Healthcare
            </button>
            {' '}
            <button data-filter='edu' aria-pressed='false'>
              Education
            </button>
            {' '}
            <button data-filter='gov' aria-pressed='false'>
              Governance
            </button>
            {' '}
            <button data-filter='city' aria-pressed='false'>
              Smart Cities
            </button>
            {' '}
            <button data-filter='energy' aria-pressed='false'>
              Energy
            </button>
            {' '}
            <button data-filter='bfsi' aria-pressed='false'>
              Banking
            </button>
          </div>
          <div className='grid g-3' id='event-grid' data-reveal-group='' aria-live='polite' aria-busy='false'>
            <article className='card card--glow event-card event-card--feature' data-cat='energy' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-01.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date'>
                  <b>
                    18
                  </b>
                  <span>
                    Aug
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Energy
                </span>
              </div>
              <div className='card__body'>
                <span className='tag tag-live'>
                  Registrations open
                </span>
                <h3>
                  <Link className='card__link' href='/events/india-energy-expo-2026' data-cursor='View'>
                    India Energy Expo 2026
                  </Link>
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  {' '}Two days on the grid of the future — storage, transmission, green hydrogen and the state utilities rebuilding their demand forecasting around AI.{' '}
                </p>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}18–19 August 2026
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}New Delhi
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-users' />
                    </svg>
                    {' '}350+ delegates
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      Delegate seats · 72% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='72'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='bfsi' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-02.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    Aug
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Banking
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/bfsi-gamechanger-summit-2026' data-cursor='View'>
                    7th Elets BFSI Gamechanger Summit
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}August 2026
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}Goa
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      58% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='58'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='edu' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-03.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    Aug
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Education
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/world-education-summit-2026' data-cursor='View'>
                    36th Elets World Education Summit
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}August 2026
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}New Delhi
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      41% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='41'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='health' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-04.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    Sep
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Healthcare
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/patient-centricity-summit-2026' data-cursor='View'>
                    2nd Elets Patient Centricity Summit & Awards
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}September 2026
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}Mumbai
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      33% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='33'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='gov' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-05.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    TBC
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Governance
                </span>
              </div>
              <div className='card__body'>
                <span className='tag tag-gov'>
                  Government track
                </span>
                <h3>
                  <Link className='card__link' href='/events/national-psu-summit-2026' data-cursor='View'>
                    Elets National PSU Summit 2026
                  </Link>
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Powering Atma Nirbhar Bharat through innovation, resilience and collaboration.
                </p>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}New Delhi
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-users' />
                    </svg>
                    {' '}50+ policymakers
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      64% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='64'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='city' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-06.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    TBC
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Smart Cities
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/urban-innovation-summit-2026' data-cursor='View'>
                    6th Elets Urban Innovation Summit 2026
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}India
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      27% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='27'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='edu gov' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-07.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    TBC
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Skills
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/national-skill-education-summit-up' data-cursor='View'>
                    National Skill & Education Summit, Uttar Pradesh
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}Lucknow
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      49% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='49'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='health' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-08.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    Dec
                  </b>
                  <span>
                    2026
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Healthcare
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/healthcare-innovation-summit-2026' data-cursor='View'>
                    19th Elets Healthcare Innovation Summit & Awards
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}December 2026
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      18% allocated
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='18'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='health' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-09.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date event-card__date--tbc'>
                  <b>
                    Mar
                  </b>
                  <span>
                    2027
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  Pharma
                </span>
              </div>
              <div className='card__body'>
                <h3>
                  <Link className='card__link' href='/events/india-pharma-expo-2027' data-cursor='View'>
                    India Pharma Expo 2027
                  </Link>
                </h3>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-cal' />
                    </svg>
                    {' '}March 2027
                  </span>
                  {' '}
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}Hyderabad
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      Early interest
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='9'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
            <article className='card card--glow event-card' data-cat='ai' data-reveal='up'>
              <div className='card__media'>
                <img src='/assets/img/events/ev-10.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                {' '}
                <span className='event-card__date'>
                  <b>
                    22
                  </b>
                  <span>
                    Jan
                  </span>
                </span>
                {' '}
                <span className='event-card__sector'>
                  AI
                </span>
              </div>
              <div className='card__body'>
                <span className='tag'>
                  Concluded · watch sessions
                </span>
                <h3>
                  <Link className='card__link' href='/events/india-ai-summit-2026' data-cursor='View'>
                    Elets India AI Summit 2026
                  </Link>
                </h3>
                <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                  Official pre-event to the India AI Impact Summit. 60+ speakers, 20+ partners.
                </p>
                <div className='event-card__meta'>
                  <span>
                    <svg width='13' height='13' aria-hidden='true'>
                      <use href='#i-pin' />
                    </svg>
                    {' '}Eros Hotel, Nehru Place, New Delhi
                  </span>
                </div>
                <div className='event-card__foot'>
                  <div className='seats'>
                    <span className='seats__label'>
                      Sold out · 350 delegates
                    </span>
                    {' '}
                    <span className='seats__bar'>
                      <span className='seats__fill' data-bar='100'></span>
                    </span>
                  </div>
                  <span className='go' aria-hidden='true'>
                    <svg width='15' height='15'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </div>
              </div>
            </article>
          </div>
          <p className='empty hide mt-6' data-empty=''>
            No events in this sector yet — try another filter.
          </p>
          <div className='text-center mt-8'>
            <Link className='btn btn-ghost btn-lg magnetic' href='/events/india-energy-expo-2026' data-magnet='0.2'>
              <span className='magnetic__inner'>
                Load the full calendar
              </span>
            </Link>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Seven practices
              </span>
              <h2 data-split=''>
                The sectors we have covered longest
              </h2>
            </div>
          </div>
          <div className='index-list' data-peek-list=''>
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-10.svg'>
              <span className='index-row__n'>
                01
              </span>
              {' '}
              <span className='index-row__t'>
                Artificial Intelligence
              </span>
              {' '}
              <span className='index-row__c'>
                India AI Summit · AI on Water
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-05.svg'>
              <span className='index-row__n'>
                02
              </span>
              {' '}
              <span className='index-row__t'>
                Governance & Public Sector
              </span>
              {' '}
              <span className='index-row__c'>
                PSU Summit · Digital Innovation
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-04.svg'>
              <span className='index-row__n'>
                03
              </span>
              {' '}
              <span className='index-row__t'>
                Healthcare & Pharma
              </span>
              {' '}
              <span className='index-row__c'>
                Healthcare Innovation · Patient Centricity
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-03.svg'>
              <span className='index-row__n'>
                04
              </span>
              {' '}
              <span className='index-row__t'>
                Education & Skilling
              </span>
              {' '}
              <span className='index-row__c'>
                World Education Summit · Campus to Career
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-02.svg'>
              <span className='index-row__n'>
                05
              </span>
              {' '}
              <span className='index-row__t'>
                Banking, NBFC & Fintech
              </span>
              {' '}
              <span className='index-row__c'>
                NBFC100 · BFSI Gamechanger · World Fintech
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-06.svg'>
              <span className='index-row__n'>
                06
              </span>
              {' '}
              <span className='index-row__t'>
                Smart & Resilient Cities
              </span>
              {' '}
              <span className='index-row__c'>
                Urban Innovation Summit
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
            {' '}
            <Link className='index-row' href='/events/india-energy-expo-2026' data-peek='/assets/img/events/ev-01.svg'>
              <span className='index-row__n'>
                07
              </span>
              {' '}
              <span className='index-row__t'>
                Energy & Infrastructure
              </span>
              {' '}
              <span className='index-row__c'>
                India Energy Expo
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
        </div>
      </section>
      <section className='band-dark noise section' aria-labelledby='scale-h'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                By the numbers
              </span>
              <h2 id='scale-h' data-split=''>
                Scale is the reason sponsors come back.
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-glass' href='/sponsors'>
                Partnership options{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <div className='stat' data-reveal='up'>
              <b data-count='1000' data-count-suf='+'>
                0
              </b>
              <span>
                Conferences convened
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='20000' data-count-suf='+'>
                0
              </b>
              <span>
                Speakers hosted
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='600000' data-count-suf='+'>
                0
              </b>
              <span>
                Delegates welcomed
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='475'>
                0
              </b>
              <span>
                Events in the archive
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='4' data-count-suf='M+'>
                0
              </b>
              <span>
                Monthly online readers
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='10' data-count-suf='M+'>
                0
              </b>
              <span>
                Session video views
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='4'>
                0
              </b>
              <span>
                Print & digital magazines
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='2'>
                0
              </b>
              <span>
                Offices — Noida & Dubai
              </span>
            </div>
          </div>
          <div className='marquee marquee--text mt-9' style={{ '--marquee-dur': '36s' } as CSSProperties} aria-hidden='true'>
            <div className='marquee__track'>
              <span className='marquee__item'>
                Governance
              </span>
              {' '}
              <span className='marquee__item is-outline'>
                Healthcare
              </span>
              {' '}
              <span className='marquee__item'>
                Education
              </span>
              {' '}
              <span className='marquee__item is-outline'>
                BFSI
              </span>
              {' '}
              <span className='marquee__item'>
                Artificial Intelligence
              </span>
              {' '}
              <span className='marquee__item is-outline'>
                Smart Cities
              </span>
              {' '}
              <span className='marquee__item'>
                Energy
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='speakers' data-rail=''>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                On our stages
              </span>
              <h2 data-split=''>
                Secretaries, CEOs and chief data scientists — in the same room
              </h2>
            </div>
            <div className='sec-head__aside flex gap-2'>
              <button className='icon-btn' data-rail-prev='' aria-label='Previous speakers'>
                <svg width='16' height='16' style={{ transform: 'rotate(180deg)' }} aria-hidden='true'>
                  <use href='#i-arrow-r' />
                </svg>
              </button>
              {' '}
              <button className='icon-btn' data-rail-next='' aria-label='Next speakers'>
                <svg width='16' height='16' aria-hidden='true'>
                  <use href='#i-arrow-r' />
                </svg>
              </button>
            </div>
          </div>
          <div className='speaker-rail' role='list' aria-label='Featured speakers'>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-01.svg' alt='Brig. B. D. Mishra' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/b-d-mishra' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/b-d-mishra' data-cursor='Profile'>
                    Brig. B. D. Mishra
                  </Link>
                </h3>
                <p>
                  Hon&apos;ble Lieutenant Governor, UT Administration Ladakh
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-04.svg' alt='Akash Tripathi, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/akash-tripathi' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/akash-tripathi' data-cursor='Profile'>
                    Akash Tripathi, IAS
                  </Link>
                </h3>
                <p>
                  CEO MyGov · MD & CEO, Digital India Corporation, MeitY
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-05.svg' alt='Thampy Koshy' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/thampy-koshy' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/thampy-koshy' data-cursor='Profile'>
                    Thampy Koshy
                  </Link>
                </h3>
                <p>
                  MD & CEO, Open Network for Digital Commerce (ONDC)
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-08.svg' alt='Dr. Rajendra Kumar, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/rajendra-kumar' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/rajendra-kumar' data-cursor='Profile'>
                    Dr. Rajendra Kumar, IAS
                  </Link>
                </h3>
                <p>
                  Secretary, Ministry of Home Affairs
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-12.svg' alt='Himanshu Pant' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/himanshu-pant' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/himanshu-pant' data-cursor='Profile'>
                    Himanshu Pant
                  </Link>
                </h3>
                <p>
                  Chief Digital Officer, Adani Group
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-13.svg' alt='Dr. Shailesh Kumar' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/shailesh-kumar' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/shailesh-kumar' data-cursor='Profile'>
                    Dr. Shailesh Kumar
                  </Link>
                </h3>
                <p>
                  Chief Data Scientist, CoE AI/ML, Jio
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-11.svg' alt='Deepak Bagla' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/deepak-bagla' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/deepak-bagla' data-cursor='Profile'>
                    Deepak Bagla
                  </Link>
                </h3>
                <p>
                  Mission Director, Atal Innovation Mission, NITI Aayog
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-10.svg' alt='D Thara, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/d-thara' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/d-thara' data-cursor='Profile'>
                    D Thara, IAS
                  </Link>
                </h3>
                <p>
                  Additional Secretary, Ministry of Housing and Urban Affairs
                </p>
              </div>
            </article>
          </div>
          <div className='flex between center wrap gap-4 mt-6'>
            <p className='mono muted'>
              Drag the rail · or use the arrows
            </p>
            <Link className='btn btn-soft' href='/speakers'>
              All speakers{' '}
              <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </Link>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Sample day
              </span>
              <h2 data-split=''>
                An Elets agenda, hour by hour
              </h2>
              <p>
                From the India Energy Expo 2026 programme. Every session expands to reveal speakers, track and room.
              </p>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-soft' href='/agenda'>
                Full agenda{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='agenda' id='agenda-preview'>
            <div className='agenda__progress' aria-hidden='true'></div>
            <article className='slot is-open track-energy'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='true'>
                <span className='slot__time'>
                  09:30 — 10:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Inaugural plenary: the grid India will need in 2035
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Energy
                    </span>
                    {' '}
                    <span className='tag'>
                      Main hall
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Ministers, regulators and state utility chairs open the Expo with the demand picture to 2035 — and what has to be procured, financed and skilled before then.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-03.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            Gaurav Gupta, IAS
                          </b>
                          <span>
                            Additional Chief Secretary, Energy, Government of Karnataka
                          </span>
                        </span>
                      </span>
                      {' '}
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-09.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            Ashok K.K. Meena
                          </b>
                          <span>
                            Secretary, Dept of Drinking Water & Sanitation, Ministry of Jal Shakti
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-ai'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  10:30 — 11:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Forecasting demand with AI: what three state utilities learned
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      AI
                    </span>
                    {' '}
                    <span className='tag'>
                      Track A
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      A working session on load forecasting models in production — data quality, procurement routes and the governance needed before a model touches dispatch.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-13.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            Dr. Shailesh Kumar
                          </b>
                          <span>
                            Chief Data Scientist, CoE AI/ML, Jio
                          </span>
                        </span>
                      </span>
                      {' '}
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-14.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            Gaurav Duggal
                          </b>
                          <span>
                            SVP & Head of Data Analytics & AI, Jio Platforms Limited
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-gov'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  11:30 — 12:15
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Public–private partnership: forging faster procurement for clean energy
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Governance
                    </span>
                    {' '}
                    <span className='tag'>
                      Track B
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Where PPP structures have unlocked capacity — and where they have stalled. Drawn from the PSU Summit&apos;s collaboration-for-innovation track.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-02.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            Amit Sharma, IAS
                          </b>
                          <span>
                            Secretary (IT, Transport, RD, S&T) & MD SIDCO, UT Administration Ladakh
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
            <article className='slot track-city'>
              <span className='slot__dot' aria-hidden='true'></span>
              {' '}
              <button className='slot__head' aria-expanded='false'>
                <span className='slot__time'>
                  14:00 — 14:45
                </span>
                {' '}
                <span>
                  <span className='slot__title'>
                    Urban energy: cooling, transport and the municipal balance sheet
                  </span>
                  {' '}
                  <span className='slot__tags'>
                    <span className='tag tag-dot'>
                      Smart Cities
                    </span>
                    {' '}
                    <span className='tag'>
                      Track A
                    </span>
                  </span>
                </span>
                {' '}
                <span className='slot__toggle' aria-hidden='true'>
                  <svg width='13' height='13'>
                    <use href='#i-plus' />
                  </svg>
                </span>
              </button>
              <div className='slot__panel'>
                <div>
                  <div className='slot__body'>
                    <p>
                      Municipal commissioners on the three line items that actually move a city&apos;s energy bill, and how they were financed.
                    </p>
                    <div className='slot__speakers'>
                      <span className='mini-speaker'>
                        <img src='/assets/img/speakers/sp-10.svg' alt='' width='42' height='42' loading='lazy' />
                        <span>
                          <b>
                            D Thara, IAS
                          </b>
                          <span>
                            Additional Secretary, Ministry of Housing and Urban Affairs
                          </span>
                        </span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
      <section className='band-dark noise section' id='videos'>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Video library · 10M+ views
              </span>
              <h2 data-split=''>
                Every keynote, kept.
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-glass' href='/videos'>
                Browse the library{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <a className='video video--hero mb-8' href='#video-modal' data-modal-open='video-modal' data-cursor='Play' data-reveal='scale'>
            <img src='/assets/img/videos/vid-01.svg' alt='AI in Governance keynote' width='1600' height='900' loading='lazy' decoding='async' />
            {' '}
            <span className='video__dur'>
              42:16
            </span>
            {' '}
            <span className='video__play'>
              <i>
                <svg width='20' height='20' aria-hidden='true'>
                  <use href='#i-play' />
                </svg>
              </i>
            </span>
            {' '}
            <span className='video__meta'>
              <h3 style={{ fontSize: 'var(--fs-lg)' }}>
                Keynote — AI in governance: from pilots to production
              </h3>
              <p>
                India AI Summit 2026 · New Delhi
              </p>
            </span>
          </a>
          <h3 className='h5 mb-4'>
            Most watched
          </h3>
          <div className='vid-row' role='list'>
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-02.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                31:04
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Inside the NBFC tech stack
                </h3>
                <p>
                  NBFC100 · Chennai
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-03.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                27:52
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Building smart wards
                </h3>
                <p>
                  Urban Innovation Summit
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-04.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                38:11
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Water intelligence
                </h3>
                <p>
                  National AI Summit on Water 2026
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-05.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                24:39
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Campus to career
                </h3>
                <p>
                  Campus to Career Summit · Bengaluru
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-06.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                45:20
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Public sector cybersecurity
                </h3>
                <p>
                  Public Sector Day · Delhi
                </p>
              </span>
            </a>
          </div>
          <h3 className='h5 mb-4 mt-6'>
            Recently added
          </h3>
          <div className='vid-row' role='list'>
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-07.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                36:58
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  The energy transition, financed
                </h3>
                <p>
                  India Energy Expo preview
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-08.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                29:12
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  The ONDC effect
                </h3>
                <p>
                  World Fintech Summit · Bengaluru
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-01.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                42:16
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  AI in governance
                </h3>
                <p>
                  India AI Summit 2026
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-03.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              {' '}
              <span className='video__dur'>
                27:52
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              {' '}
              <span className='video__meta'>
                <h3>
                  Building smart wards
                </h3>
                <p>
                  Urban Innovation Summit
                </p>
              </span>
            </a>
          </div>
        </div>
      </section>
      <section className='section' id='magazines'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Four titles · 4M+ monthly readers
              </span>
              <h2 data-split=''>
                The magazines behind the conferences
              </h2>
              <p>
                eGov, digitalLEARNING, eHEALTH and The Banking & Finance Post have been reporting these sectors since long before the summits existed.
              </p>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-soft' href='/magazines'>
                Full library{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <span className='mag__ribbon'>
                  Latest
                </span>
                {' '}
                <img src='/assets/img/magazines/mag-01.svg' alt='eGov, July 2026 — The AI-Ready State' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  eGov · July 2026
                </span>
                <h3 className='mt-2'>
                  The AI-Ready State
                </h3>
                <div className='mag__actions'>
                  <Link className='btn btn-soft btn-sm' href='/magazines'>
                    Read online
                  </Link>
                  {' '}
                  <Link className='btn btn-soft btn-sm' href='/magazines' aria-label='Download PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </Link>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-02.svg' alt='digitalLEARNING, July 2026 — Campus to Career' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  digitalLEARNING · July 2026
                </span>
                <h3 className='mt-2'>
                  Campus to Career
                </h3>
                <div className='mag__actions'>
                  <Link className='btn btn-soft btn-sm' href='/magazines'>
                    Read online
                  </Link>
                  {' '}
                  <Link className='btn btn-soft btn-sm' href='/magazines' aria-label='Download PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </Link>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-03.svg' alt='eHEALTH, June 2026 — Patient First by Design' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  eHEALTH · June 2026
                </span>
                <h3 className='mt-2'>
                  Patient First by Design
                </h3>
                <div className='mag__actions'>
                  <Link className='btn btn-soft btn-sm' href='/magazines'>
                    Read online
                  </Link>
                  {' '}
                  <Link className='btn btn-soft btn-sm' href='/magazines' aria-label='Download PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </Link>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-04.svg' alt='The Banking & Finance Post, June 2026 — The NBFC Tech Stack' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  BFSI Post · June 2026
                </span>
                <h3 className='mt-2'>
                  The NBFC Tech Stack
                </h3>
                <div className='mag__actions'>
                  <Link className='btn btn-soft btn-sm' href='/magazines'>
                    Read online
                  </Link>
                  {' '}
                  <Link className='btn btn-soft btn-sm' href='/magazines' aria-label='Download PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </Link>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
      <section className='section' id='sponsors'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Partners
              </span>
              <h2 data-split=''>
                Brands that build their year around these rooms
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-primary magnetic' href='/sponsors' data-magnet='0.22'>
                <span className='magnetic__inner'>
                  Become a partner{' '}
                  <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </span>
              </Link>
            </div>
          </div>
          <p className='mono muted mb-4'>
            Presenting & platform partners
          </p>
          <div className='marquee mb-8' style={{ '--marquee-dur': '38s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-02.svg' alt='Confluent' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-03.svg' alt='Infinity Labs' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-04.svg' alt='ESDS' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-05.svg' alt='Karix' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-06.svg' alt='Chat360' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
          <p className='mono muted mb-4'>
            Institutions represented on our stages
          </p>
          <div className='marquee marquee--reverse' style={{ '--marquee-dur': '46s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-07.svg' alt='Digital India' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-08.svg' alt='MyGov' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-09.svg' alt='ONDC' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-10.svg' alt='NITI Aayog' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-11.svg' alt='MeitY' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-12.svg' alt='FSSAI' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                From the floor
              </span>
              <h2 data-split=''>
                What delegates say afterwards
              </h2>
            </div>
          </div>
          <div className='grid g-3' data-reveal-group=''>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “The only forum where I can put a procurement question to three states and a platform vendor in the same afternoon.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-06.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                {' '}
                <span>
                  <b>
                    Principal Secretary, IT
                  </b>
                  <span>
                    State Government · Delegate, 2026
                  </span>
                </span>
              </figcaption>
            </figure>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “We booked two hospital deployments off conversations that started at the Healthcare Innovation Summit.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-15.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                {' '}
                <span>
                  <b>
                    Chief Technology Officer
                  </b>
                  <span>
                    Health-tech platform · Partner, 2026
                  </span>
                </span>
              </figcaption>
            </figure>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “Elets understands that a vice-chancellor and a CIO need different sessions on the same day. The agenda respects that.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-07.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                {' '}
                <span>
                  <b>
                    Vice-Chancellor
                  </b>
                  <span>
                    Central University · Speaker, 2026
                  </span>
                </span>
              </figcaption>
            </figure>
          </div>
          <p className='mono dim text-center mt-6'>
            Quotations shown are placeholder copy for design review.
          </p>
        </div>
      </section>
      <section className='section' id='news'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                News & insights
              </span>
              <h2 data-split=''>
                Reporting from inside the room
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='link' href='/news'>
                All coverage{' '}
                <svg width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <Link className='news news--hero mb-8' href='/news' data-cursor='Read' data-reveal='up'>
            <span className='news__media'>
              <img src='/assets/img/events/ev-11.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
            </span>
            {' '}
            <span>
              <span className='news__meta'>
                <span>
                  Governance
                </span>
                <span>
                  ·
                </span>
                <span>
                  6 min read
                </span>
              </span>
              <h3>
                Uttar Pradesh showcases its AI leadership at the 3rd National Digital Innovation Summit 2026
              </h3>
              <p className='lead mt-4'>
                Lucknow, 17 July. The state set out its AI, innovation and digital infrastructure roadmap in front of central and state officials — and the private platforms hoping to build it.
              </p>
              <span className='link mt-4'>
                Read the report{' '}
                <svg width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </span>
            </span>
          </Link>
          <div className='grid g-3' data-reveal-group=''>
            <Link className='news' href='/news' data-cursor='Read' data-reveal='up'>
              <span className='news__media'>
                <img src='/assets/img/events/ev-10.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='news__meta'>
                <span>
                  AI
                </span>
                <span>
                  ·
                </span>
                <span>
                  4 min read
                </span>
              </span>
              <h3>
                Elets Technomedia&apos;s India AI Summit 2026 named official pre-event to the India AI Impact Summit
              </h3>
            </Link>
            {' '}
            <Link className='news' href='/news' data-cursor='Read' data-reveal='up'>
              <span className='news__media'>
                <img src='/assets/img/events/ev-05.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='news__meta'>
                <span>
                  Public sector
                </span>
                <span>
                  ·
                </span>
                <span>
                  5 min read
                </span>
              </span>
              <h3>
                Elastic Public Sector Day 2026 concludes, spotlighting AI-driven cybersecurity for government
              </h3>
            </Link>
            {' '}
            <Link className='news' href='/news' data-cursor='Read' data-reveal='up'>
              <span className='news__media'>
                <img src='/assets/img/events/ev-07.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='news__meta'>
                <span>
                  Education
                </span>
                <span>
                  ·
                </span>
                <span>
                  3 min read
                </span>
              </span>
              <h3>
                Karnataka hosts Campus to Career Summit 2026 in Bengaluru
              </h3>
            </Link>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                Three ways in
              </span>
              <h2 className='mt-5' data-split=''>
                Attend. Speak. Or put your brand in the room.
              </h2>
              <p>
                Delegate passes, speaking submissions and partnership decks — all handled by the same secretariat.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg magnetic' href='/registration' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Register as delegate{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/registration#speaking'>
                  Submit to speak
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/sponsors'>
                  Partnership deck
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
