/* eslint-disable */
/**
 * MagazinesBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function MagazinesBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell shell-wide relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                Media
              </li>
              <li aria-current='page'>
                Magazine library
              </li>
            </ol>
          </nav>
          <div className='grid split' style={{ '--split': 'minmax(0,1.15fr) minmax(0,.85fr)', gap: 'clamp(2rem,4vw,4.5rem)', alignItems: 'center' } as CSSProperties}>
            <div>
              <h1 data-split=''>
                Four titles.{' '}
                <em className='serif-i grad-text'>
                  Four million
                </em>
                {' '}readers a month.
              </h1>
              <p className='lead'>
                {' '}eGov, digitalLEARNING, eHEALTH and The Banking & Finance Post have reported these sectors since long before the summits existed. Read online free, or download the PDF edition.{' '}
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <a className='btn btn-primary btn-lg magnetic' href='#subscribe' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Subscribe free{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </a>
                {' '}
                <a className='btn btn-ghost btn-lg' href='#archive'>
                  Browse the archive
                </a>
              </div>
            </div>
            <div className='mag' data-tilt='12' data-reveal='scale' style={{ maxWidth: '340px', marginInline: 'auto' }}>
              <div className='mag__cover'>
                <span className='mag__ribbon'>
                  Latest
                </span>
                {' '}
                <img src='/assets/img/magazines/mag-01.svg' alt='eGov, July 2026 — The AI-Ready State' width='960' height='1280' fetchPriority='high' decoding='async' />
              </div>
              <div className='mag__info text-center'>
                <span className='mono muted'>
                  eGov · July 2026
                </span>
                <h3 className='mt-2'>
                  The AI-Ready State
                </h3>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-8)' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                The four titles
              </span>
              <h2 data-split=''>
                What each one covers
              </h2>
            </div>
          </div>
          <div className='index-list' data-peek-list=''>
            <a className='index-row' href='#archive' data-peek='/assets/img/magazines/mag-01.svg'>
              <span className='index-row__n'>
                01
              </span>
              <span className='index-row__t'>
                eGov
              </span>
              {' '}
              <span className='index-row__c'>
                E-governance, public sector technology, smart cities
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </a>
            {' '}
            <a className='index-row' href='#archive' data-peek='/assets/img/magazines/mag-02.svg'>
              <span className='index-row__n'>
                02
              </span>
              <span className='index-row__t'>
                digitalLEARNING
              </span>
              {' '}
              <span className='index-row__c'>
                Higher education, skilling, edtech and employability
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </a>
            {' '}
            <a className='index-row' href='#archive' data-peek='/assets/img/magazines/mag-03.svg'>
              <span className='index-row__n'>
                03
              </span>
              <span className='index-row__t'>
                eHEALTH
              </span>
              {' '}
              <span className='index-row__c'>
                Hospital systems, health policy, medtech and pharma
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </a>
            {' '}
            <a className='index-row' href='#archive' data-peek='/assets/img/magazines/mag-04.svg'>
              <span className='index-row__n'>
                04
              </span>
              <span className='index-row__t'>
                The Banking & Finance Post
              </span>
              {' '}
              <span className='index-row__c'>
                Banking, NBFC, insurance and fintech
              </span>
              {' '}
              <svg width='17' height='17' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </a>
          </div>
        </div>
      </section>
      <section className='section' id='archive' style={{ paddingTop: '0' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Editions
              </span>
              <h2 data-split=''>
                The archive
              </h2>
            </div>
            <div className='sec-head__aside' style={{ minWidth: '280px' }}>
              <div className='search'>
                <svg width='16' height='16' aria-hidden='true'>
                  <use href='#i-search' />
                </svg>
                {' '}
                <label className='sr-only' htmlFor='m-search'>
                  Search editions
                </label>
                {' '}
                <input className='input' id='m-search' type='search' placeholder='Search editions…' data-search='#mag-grid' />
              </div>
            </div>
          </div>
          <div className='filters mb-8' data-filters='#mag-grid' role='group' aria-label='Filter by title'>
            <span className='filters__pill' aria-hidden='true'></span>
            {' '}
            <button data-filter='all' aria-pressed='true'>
              All titles
            </button>
            {' '}
            <button data-filter='egov' aria-pressed='false'>
              eGov
            </button>
            {' '}
            <button data-filter='dl' aria-pressed='false'>
              digitalLEARNING
            </button>
            {' '}
            <button data-filter='eh' aria-pressed='false'>
              eHEALTH
            </button>
            {' '}
            <button data-filter='bfsi' aria-pressed='false'>
              Banking & Finance Post
            </button>
          </div>
          <div className='grid g-3' id='mag-grid' data-reveal-group='' aria-live='polite'>
            <article className='mag' data-tilt='10' data-cat='egov' data-search-text='eGov July 2026 The AI-Ready State' data-reveal='up'>
              <div className='mag__cover'>
                <span className='mag__ribbon'>
                  Latest
                </span>
                {' '}
                <img src='/assets/img/magazines/mag-01.svg' alt='eGov, July 2026 — The AI-Ready State' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  eGov · July 2026
                </span>
                <h3 className='mt-2'>
                  The AI-Ready State
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  How states are moving from AI pilots to production services.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download eGov July 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-cat='dl' data-search-text='digitalLEARNING July 2026 Campus to Career' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-02.svg' alt='digitalLEARNING, July 2026 — Campus to Career' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  digitalLEARNING · July 2026
                </span>
                <h3 className='mt-2'>
                  Campus to Career
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  Employability, apprenticeships and the widening gap between syllabus and job.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download digitalLEARNING July 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-cat='eh' data-search-text='eHEALTH June 2026 Patient First by Design' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-03.svg' alt='eHEALTH, June 2026 — Patient First by Design' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  eHEALTH · June 2026
                </span>
                <h3 className='mt-2'>
                  Patient First by Design
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  Designing hospital systems around the patient rather than the department.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download eHEALTH June 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-cat='bfsi' data-search-text='The Banking & Finance Post June 2026 The NBFC Tech Stack' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-04.svg' alt='The Banking & Finance Post, June 2026 — The NBFC Tech Stack' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  The Banking & Finance Post · June 2026
                </span>
                <h3 className='mt-2'>
                  The NBFC Tech Stack
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  What the 100 largest NBFCs actually run, and what they are replacing.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download The Banking & Finance Post June 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-cat='egov' data-search-text='eGov May 2026 Water, Data and AI' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-05.svg' alt='eGov, May 2026 — Water, Data and AI' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  eGov · May 2026
                </span>
                <h3 className='mt-2'>
                  Water, Data and AI
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  Distribution-network intelligence, from the National AI Summit on Water.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download eGov May 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
            <article className='mag' data-tilt='10' data-cat='dl' data-search-text='digitalLEARNING April 2026 Skilling Bharat' data-reveal='up'>
              <div className='mag__cover'>
                <img src='/assets/img/magazines/mag-06.svg' alt='digitalLEARNING, April 2026 — Skilling Bharat' width='960' height='1280' loading='lazy' decoding='async' />
              </div>
              <div className='mag__info'>
                <span className='mono muted'>
                  digitalLEARNING · April 2026
                </span>
                <h3 className='mt-2'>
                  Skilling Bharat
                </h3>
                <p className='muted mt-2' style={{ fontSize: 'var(--fs-xs)' }}>
                  The ITI and polytechnic system, measured against what employers hire for.
                </p>
                <div className='mag__actions'>
                  <a className='btn btn-soft btn-sm' href='#'>
                    Read online
                  </a>
                  {' '}
                  <a className='btn btn-soft btn-sm' href='#' aria-label='Download digitalLEARNING April 2026 as PDF'>
                    <svg width='14' height='14' aria-hidden='true'>
                      <use href='#i-dl' />
                    </svg>
                  </a>
                </div>
              </div>
            </article>
          </div>
          <p className='empty hide mt-6' data-empty=''>
            No editions match that filter.
          </p>
          <nav className='pager mt-9' aria-label='Pagination'>
            <a href='#' aria-current='page'>
              1
            </a>
            <a href='#'>
              2
            </a>
            <a href='#'>
              3
            </a>
            {' '}
            <span aria-hidden='true'>
              …
            </span>
            <a href='#'>
              124
            </a>
            {' '}
            <a href='#' aria-label='Next page'>
              <svg width='15' height='15' aria-hidden='true'>
                <use href='#i-arrow-r' />
              </svg>
            </a>
          </nav>
        </div>
      </section>
      <section className='band-dark noise section' id='subscribe'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-narrow relative'>
          <div className='text-center'>
            <span className='eyebrow' style={{ justifyContent: 'center' }}>
              Free to public sector
            </span>
            <h2 className='h2 mt-5' data-split=''>
              Get every edition in your inbox
            </h2>
            <p className='lead mx-auto mt-5' style={{ textAlign: 'center' }}>
              {' '}Choose the titles you want. Serving officers and academic institutions receive the print edition free on request.{' '}
            </p>
          </div>
          <form className='mt-8' data-demo='Subscribed — the next edition will arrive on publication.'>
            <div className='grid g-2'>
              <div className='field'>
                <label htmlFor='s-name'>
                  Name{' '}
                  <span className='req'>
                    *
                  </span>
                </label>
                <input className='input' id='s-name' name='name' required autoComplete='name' />
              </div>
              <div className='field'>
                <label htmlFor='s-email'>
                  Email{' '}
                  <span className='req'>
                    *
                  </span>
                </label>
                <input className='input' id='s-email' name='email' type='email' required autoComplete='email' />
              </div>
            </div>
            <fieldset className='mt-6' style={{ border: '0', padding: '0', margin: '0' }}>
              <legend className='mono muted mb-4'>
                Which titles?
              </legend>
              <div className='grid g-2'>
                <label className='check'>
                  <input type='checkbox' defaultChecked />
                  <span>
                    eGov — governance & public sector technology
                  </span>
                </label>
                {' '}
                <label className='check'>
                  <input type='checkbox' />
                  <span>
                    digitalLEARNING — education & skilling
                  </span>
                </label>
                {' '}
                <label className='check'>
                  <input type='checkbox' />
                  <span>
                    eHEALTH — hospitals, policy & medtech
                  </span>
                </label>
                {' '}
                <label className='check'>
                  <input type='checkbox' />
                  <span>
                    The Banking & Finance Post — BFSI
                  </span>
                </label>
              </div>
            </fieldset>
            <label className='check mt-5'>
              <input type='checkbox' />
              <span>
                I am a serving government officer or at an academic institution — send the print edition free.
              </span>
            </label>
            {' '}
            <button className='btn btn-brand btn-lg mt-6' type='submit'>
              Subscribe{' '}
              <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                <use href='#i-arrow' />
              </svg>
            </button>
          </form>
        </div>
      </section>
    </>
  );
}
