/* eslint-disable */
/**
 * RegistrationBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function RegistrationBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/events/india-energy-expo-2026'>
                  India Energy Expo 2026
                </Link>
              </li>
              <li aria-current='page'>
                Registration
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            Register for{' '}
            <em className='serif-i grad-text'>
              India Energy Expo 2026
            </em>
          </h1>
          <p className='lead'>
            18–19 August 2026 · New Delhi. Government officers attend free. Seats are allocated in the order applications are approved.
          </p>
          <div className='countdown mt-8' data-countdown='2026-08-18T09:30:00+05:30' role='timer' style={{ maxWidth: '420px' }}>
            <div className='cd-unit'>
              <b data-cd='d'>
                00
              </b>
              <span>
                Days
              </span>
            </div>
            <div className='cd-unit'>
              <b data-cd='h'>
                00
              </b>
              <span>
                Hrs
              </span>
            </div>
            <div className='cd-unit'>
              <b data-cd='m'>
                00
              </b>
              <span>
                Min
              </span>
            </div>
            <div className='cd-unit'>
              <b data-cd='s'>
                00
              </b>
              <span>
                Sec
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-8)' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Delegate categories
              </span>
              <h2 data-split=''>
                Choose your pass
              </h2>
            </div>
            <div className='sec-head__aside'>
              <p className='mono muted'>
                All rates exclusive of GST
              </p>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <div className='price' data-reveal='up'>
              <span className='tag tag-gov' style={{ alignSelf: 'start' }}>
                Government
              </span>
              <h3 className='h4'>
                Public sector
              </h3>
              <div className='price__amt'>
                <b>
                  Free
                </b>
                <span>
                  invitation-based
                </span>
              </div>
              <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                For serving officers of central and state government, PSUs and regulatory bodies.
              </p>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Full access, both days
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Awards night included
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Roundtable eligibility
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Session recordings
                </li>
              </ul>
              <a className='btn btn-soft btn-block mt-4' href='#register-form'>
                Apply with official email
              </a>
            </div>
            <div className='price price--featured' data-reveal='up'>
              <span className='tag tag-solid' style={{ alignSelf: 'start' }}>
                Most chosen
              </span>
              <h3 className='h4'>
                Delegate
              </h3>
              <div className='price__amt'>
                <b>
                  ₹24,000
                </b>
                <span>
                  per person
                </span>
              </div>
              <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                Standard industry pass for both conference days and the exhibition floor.
              </p>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Full access, both days
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Awards night included
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Delegate list (opt-in)
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Session recordings
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Post-event written summary
                </li>
              </ul>
              <a className='btn btn-brand btn-block mt-4' href='#register-form'>
                Register now
              </a>
            </div>
            <div className='price' data-reveal='up'>
              <h3 className='h4'>
                Team of four
              </h3>
              <div className='price__amt'>
                <b>
                  ₹78,000
                </b>
                <span>
                  four passes
                </span>
              </div>
              <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                Bring the people who will actually implement what they hear.
              </p>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Everything in Delegate ×4
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}One name change free
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Reserved table at dinner
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}19% saving
                </li>
              </ul>
              <a className='btn btn-soft btn-block mt-4' href='#register-form'>
                Book for a team
              </a>
            </div>
            <div className='price' data-reveal='up'>
              <h3 className='h4'>
                Partner & exhibitor
              </h3>
              <div className='price__amt'>
                <b>
                  On request
                </b>
                <span>
                  tiered
                </span>
              </div>
              <p className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                Stand space, speaking slots and branding across the magazine and video library.
              </p>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Exhibition stand
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Delegate passes included
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Speaking slot (tier-dependent)
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Year-round media placement
                </li>
              </ul>
              <Link className='btn btn-soft btn-block mt-4' href='/sponsors'>
                See partnership tiers
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='register-form' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div className='grid split' style={{ '--split': 'minmax(0,1.4fr) minmax(0,.6fr)', gap: 'clamp(2rem,4vw,4rem)', alignItems: 'start' } as CSSProperties}>
            <div>
              <form data-stepper='' noValidate>
                <ol className='steps' aria-label='Registration progress'>
                  <li className='step is-active'>
                    <span className='step__n'>
                      1
                    </span>
                    <span className='step__l'>
                      Your details
                    </span>
                    <span className='step__bar'></span>
                  </li>
                  <li className='step'>
                    <span className='step__n'>
                      2
                    </span>
                    <span className='step__l'>
                      Pass
                    </span>
                    <span className='step__bar'></span>
                  </li>
                  <li className='step'>
                    <span className='step__n'>
                      3
                    </span>
                    <span className='step__l'>
                      Stay & extras
                    </span>
                    <span className='step__bar'></span>
                  </li>
                  <li className='step'>
                    <span className='step__n'>
                      4
                    </span>
                    <span className='step__l'>
                      Review
                    </span>
                  </li>
                </ol>
                <fieldset className='pane is-active' style={{ border: '0', padding: '0', margin: '0' }}>
                  <legend className='h4 mb-5'>
                    Who is attending?
                  </legend>
                  <div className='field-row'>
                    <div className='field'>
                      <label htmlFor='fname'>
                        First name{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='fname' name='fname' required autoComplete='given-name' />
                    </div>
                    <div className='field'>
                      <label htmlFor='lname'>
                        Last name{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='lname' name='lname' required autoComplete='family-name' />
                    </div>
                  </div>
                  <div className='field-row mt-5'>
                    <div className='field'>
                      <label htmlFor='email'>
                        Work email{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='email' name='email' type='email' required autoComplete='email' placeholder='you@organisation.gov.in' />
                      <span className='hint'>
                        Use your official address to be assessed for the government rate.
                      </span>
                    </div>
                    <div className='field'>
                      <label htmlFor='phone'>
                        Mobile{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='phone' name='phone' type='tel' required autoComplete='tel' placeholder='+91' />
                    </div>
                  </div>
                  <div className='field-row mt-5'>
                    <div className='field'>
                      <label htmlFor='org'>
                        Organisation{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='org' name='org' required autoComplete='organization' />
                    </div>
                    <div className='field'>
                      <label htmlFor='desig'>
                        Designation{' '}
                        <span className='req'>
                          *
                        </span>
                      </label>
                      <input className='input' id='desig' name='desig' required autoComplete='organization-title' />
                    </div>
                  </div>
                  <div className='field-row mt-5'>
                    <div className='field'>
                      <label htmlFor='sector'>
                        Sector
                      </label>
                      <select className='select' id='sector' name='sector'>
                        <option>
                          Government / PSU
                        </option>
                        <option>
                          Utility or operator
                        </option>
                        <option>
                          Technology / OEM
                        </option>
                        <option>
                          Finance & advisory
                        </option>
                        <option>
                          Academia
                        </option>
                        <option>
                          Media
                        </option>
                        <option>
                          Other
                        </option>
                      </select>
                    </div>
                    <div className='field'>
                      <label htmlFor='city'>
                        City
                      </label>
                      <input className='input' id='city' name='city' autoComplete='address-level2' />
                    </div>
                  </div>
                </fieldset>
                <fieldset className='pane' style={{ border: '0', padding: '0', margin: '0' }}>
                  <legend className='h4 mb-5'>
                    Which pass?
                  </legend>
                  <div className='grid g-2'>
                    <label className='opt'>
                      <input type='radio' name='pass' defaultValue='gov' data-label='Public sector' data-price='Free' required />
                      <span className='opt__box'>
                        <b>
                          Public sector — free
                        </b>
                        <span>
                          Serving officers, PSUs and regulators. Verified against your official email domain.
                        </span>
                      </span>
                    </label>
                    {' '}
                    <label className='opt'>
                      <input type='radio' name='pass' defaultValue='delegate' data-label='Delegate' data-price='₹24,000' defaultChecked />
                      <span className='opt__box'>
                        <b>
                          Delegate — ₹24,000
                        </b>
                        <span>
                          Both conference days, exhibition floor and the awards night.
                        </span>
                      </span>
                    </label>
                    {' '}
                    <label className='opt'>
                      <input type='radio' name='pass' defaultValue='team' data-label='Team of four' data-price='₹78,000' />
                      <span className='opt__box'>
                        <b>
                          Team of four — ₹78,000
                        </b>
                        <span>
                          Four passes, one free name change, reserved table at dinner.
                        </span>
                      </span>
                    </label>
                    {' '}
                    <label className='opt'>
                      <input type='radio' name='pass' defaultValue='partner' data-label='Partner / exhibitor' data-price='On request' />
                      <span className='opt__box'>
                        <b>
                          Partner or exhibitor
                        </b>
                        <span>
                          The team will send the current tier grid and call you back.
                        </span>
                      </span>
                    </label>
                  </div>
                  <div className='field mt-6'>
                    <label htmlFor='tracks'>
                      Which tracks interest you most?
                    </label>
                    <select className='select' id='tracks' name='tracks'>
                      <option>
                        Grid & storage
                      </option>
                      <option>
                        AI & data
                      </option>
                      <option>
                        Policy & finance
                      </option>
                      <option>
                        Urban energy
                      </option>
                      <option>
                        All of them
                      </option>
                    </select>
                    <span className='hint'>
                      Used to balance room sizes — not binding on the day.
                    </span>
                  </div>
                  <label className='check mt-5'>
                    <input type='checkbox' name='roundtable' />
                    <span>
                      Request an invitation to the closed-door green hydrogen roundtable (20 seats, Chatham House Rule).
                    </span>
                  </label>
                </fieldset>
                <fieldset className='pane' style={{ border: '0', padding: '0', margin: '0' }}>
                  <legend className='h4 mb-5'>
                    Stay, access and extras
                  </legend>
                  <div className='field'>
                    <label htmlFor='hotel'>
                      Hotel block
                    </label>
                    <select className='select' id='hotel' name='hotel'>
                      <option>
                        No accommodation needed
                      </option>
                      <option>
                        Partner hotel — standard room
                      </option>
                      <option>
                        Partner hotel — executive room
                      </option>
                      <option>
                        Send me the rates, I&apos;ll decide later
                      </option>
                    </select>
                    <span className='hint'>
                      Block rates are held until four weeks before the event.
                    </span>
                  </div>
                  <div className='field-row mt-5'>
                    <div className='field'>
                      <label htmlFor='arrive'>
                        Arriving
                      </label>
                      <input className='input' id='arrive' name='arrive' type='date' defaultValue='2026-08-17' />
                    </div>
                    <div className='field'>
                      <label htmlFor='depart'>
                        Departing
                      </label>
                      <input className='input' id='depart' name='depart' type='date' defaultValue='2026-08-20' />
                    </div>
                  </div>
                  <div className='field mt-5'>
                    <label htmlFor='access'>
                      Accessibility or dietary requirements
                    </label>
                    <textarea className='textarea' id='access' name='access' placeholder='Step-free routing, hearing loop, dietary needs, anything else we should arrange.'></textarea>
                  </div>
                  <label className='check mt-5'>
                    <input type='checkbox' name='list' defaultChecked />
                    <span>
                      Include me on the delegate list circulated to attendees (name, designation and organisation only).
                    </span>
                  </label>
                  {' '}
                  <label className='check mt-3'>
                    <input type='checkbox' name='news' defaultChecked />
                    <span>
                      Send me the monthly calendar drop from Elets. No sponsor mail.
                    </span>
                  </label>
                </fieldset>
                <fieldset className='pane' style={{ border: '0', padding: '0', margin: '0' }}>
                  <legend className='h4 mb-5'>
                    Review and confirm
                  </legend>
                  <div className='card' style={{ padding: 'var(--sp-5)' }} data-summary=''>
                    <h3 className='h5 mb-4'>
                      Your registration
                    </h3>
                    <dl style={{ display: 'grid', gap: '.8rem', fontSize: 'var(--fs-sm)' }}>
                      <div className='flex between gap-3' data-summary-row='fname'>
                        <dt className='muted'>
                          First name
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='lname'>
                        <dt className='muted'>
                          Last name
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='email'>
                        <dt className='muted'>
                          Email
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='org'>
                        <dt className='muted'>
                          Organisation
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='desig'>
                        <dt className='muted'>
                          Designation
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='pass'>
                        <dt className='muted'>
                          Pass
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                      <div className='flex between gap-3' data-summary-row='hotel'>
                        <dt className='muted'>
                          Accommodation
                        </dt>
                        <dd data-summary-val=''>
                          —
                        </dd>
                      </div>
                    </dl>
                    <div className='rule mt-5 mb-5'></div>
                    <div className='flex between center'>
                      <span className='mono muted'>
                        Amount due
                      </span>
                      {' '}
                      <strong style={{ fontSize: 'var(--fs-xl)', letterSpacing: '-.04em' }} data-summary-total=''>
                        ₹24,000
                      </strong>
                    </div>
                  </div>
                  <h3 className='h5 mt-8 mb-4'>
                    Payment
                  </h3>
                  <div className='grid g-2'>
                    <label className='opt'>
                      <input type='radio' name='pay' defaultValue='invoice' defaultChecked />
                      <span className='opt__box'>
                        <b>
                          Raise an invoice
                        </b>
                        <span>
                          Standard for government and PSU delegates. Net 30.
                        </span>
                      </span>
                    </label>
                    {' '}
                    <label className='opt'>
                      <input type='radio' name='pay' defaultValue='card' />
                      <span className='opt__box'>
                        <b>
                          Card or UPI
                        </b>
                        <span>
                          Secure gateway. You&apos;ll be redirected after confirming.
                        </span>
                      </span>
                    </label>
                  </div>
                  <label className='check mt-6'>
                    <input type='checkbox' required />
                    <span>
                      I accept the delegate terms and the event code of conduct, and confirm the details above are correct.{' '}
                      <span className='req'>
                        *
                      </span>
                    </span>
                  </label>
                </fieldset>
                <div className='flex between center gap-3 mt-8'>
                  <button className='btn btn-soft' type='button' data-step-prev=''>
                    Back
                  </button>
                  <div className='flex gap-3'>
                    <button className='btn btn-primary btn-lg' type='button' data-step-next=''>
                      Continue{' '}
                      <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                        <use href='#i-arrow-r' />
                      </svg>
                    </button>
                    {' '}
                    <button className='btn btn-brand btn-lg hide' type='submit' data-step-submit=''>
                      Confirm registration{' '}
                      <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                        <use href='#i-check' />
                      </svg>
                    </button>
                  </div>
                </div>
              </form>
              <div className='hide' data-step-done=''>
                <div className='card text-center' style={{ padding: 'clamp(2rem,5vw,4rem)' }}>
                  <div className='tick'>
                    <svg width='34' height='34' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2.4' strokeLinecap='round' strokeLinejoin='round'>
                      <path d='M20 6L9 17l-5-5' />
                    </svg>
                  </div>
                  <h2 className='h3 mt-6'>
                    You&apos;re on the list.
                  </h2>
                  <p className='lead mx-auto mt-4' style={{ textAlign: 'center' }}>
                    {' '}A confirmation is on its way to your inbox. The secretariat reviews public sector applications within two working days and will confirm your seat.{' '}
                  </p>
                  <div className='flex wrap gap-3 mt-8' style={{ justifyContent: 'center' }}>
                    <Link className='btn btn-primary' href='/agenda'>
                      Build your agenda{' '}
                      <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <Link className='btn btn-ghost' href='/events/india-energy-expo-2026'>
                      Back to the event
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <aside className='side-sticky stack-lg'>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <span className='eyebrow'>
                  India Energy Expo 2026
                </span>
                <dl className='mt-4' style={{ display: 'grid', gap: '.8rem', fontSize: 'var(--fs-sm)' }}>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Dates
                    </dt>
                    <dd>
                      <strong>
                        18–19 Aug 2026
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Venue
                    </dt>
                    <dd>
                      <strong>
                        New Delhi
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Delegates
                    </dt>
                    <dd>
                      <strong>
                        350+
                      </strong>
                    </dd>
                  </div>
                </dl>
                <div className='mt-5'>
                  <span className='seats__label'>
                    Seats · 72% allocated
                  </span>
                  {' '}
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar='72'></span>
                  </span>
                </div>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Need a hand?
                </h3>
                <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                  The registration desk answers within one working day.
                </p>
                <p className='mt-4' style={{ fontSize: 'var(--fs-sm)' }}>
                  <a className='link' href='mailto:registration@eletsonline.com'>
                    registration@eletsonline.com
                  </a>
                  <br />
                  {' '}
                  <a className='link' href='tel:+919289955093'>
                    +91 92899 55093
                  </a>
                </p>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Cancellation
                </h3>
                <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                  Full refund up to 21 days before. After that, transfer the pass to a colleague at no charge up to 48 hours before the first session.
                </p>
              </div>
            </aside>
          </div>
        </div>
      </section>
      <section className='band-dark noise section' id='speaking'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Not attending as a delegate?
              </span>
              <h2 data-split=''>
                Three other doors in
              </h2>
            </div>
          </div>
          <div className='grid g-3' data-reveal-group=''>
            <form className='card' style={{ background: 'transparent', borderColor: 'var(--line)', padding: 'var(--sp-5)' }} data-demo='Submission received — the programme committee reviews fortnightly.' data-reveal='up'>
              <span className='mega__ico' style={{ background: 'rgba(255,255,255,.08)', color: '#fff' }}>
                <svg width='17' height='17' aria-hidden='true'>
                  <use href='#i-mic' />
                </svg>
              </span>
              <h3 className='h5 mt-4'>
                Speak at an Elets event
              </h3>
              <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                Tell us the argument you want to make. Product pitches are declined.
              </p>
              <div className='field mt-5'>
                <label className='sr-only' htmlFor='sp-name'>
                  Name
                </label>
                <input className='input' id='sp-name' name='name' required placeholder='Your name' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='sp-email'>
                  Email
                </label>
                <input className='input' id='sp-email' name='email' type='email' required placeholder='Work email' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='sp-topic'>
                  Topic
                </label>
                <textarea className='textarea' id='sp-topic' name='topic' required placeholder='Proposed session and why this room needs it' style={{ minHeight: '96px' }}></textarea>
              </div>
              <button className='btn btn-brand btn-block mt-4' type='submit'>
                Submit proposal
              </button>
            </form>
            <form className='card' style={{ background: 'transparent', borderColor: 'var(--line)', padding: 'var(--sp-5)' }} data-demo='Thanks — the partnerships team will send the deck today.' data-reveal='up'>
              <span className='mega__ico' style={{ background: 'rgba(255,255,255,.08)', color: '#fff' }}>
                <svg width='17' height='17' aria-hidden='true'>
                  <use href='#i-spark' />
                </svg>
              </span>
              <h3 className='h5 mt-4'>
                Sponsor or exhibit
              </h3>
              <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                Ask for the current tier grid, audience profile and stand plan.
              </p>
              <div className='field mt-5'>
                <label className='sr-only' htmlFor='sn-name'>
                  Name
                </label>
                <input className='input' id='sn-name' name='name' required placeholder='Your name' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='sn-email'>
                  Email
                </label>
                <input className='input' id='sn-email' name='email' type='email' required placeholder='Work email' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='sn-org'>
                  Organisation
                </label>
                <input className='input' id='sn-org' name='org' required placeholder='Organisation' />
              </div>
              <button className='btn btn-glass btn-block mt-4' type='submit'>
                Request the deck
              </button>
            </form>
            <form className='card' style={{ background: 'transparent', borderColor: 'var(--line)', padding: 'var(--sp-5)' }} data-demo='Noted — the desk will confirm your booking code by email.' data-reveal='up'>
              <span className='mega__ico' style={{ background: 'rgba(255,255,255,.08)', color: '#fff' }}>
                <svg width='17' height='17' aria-hidden='true'>
                  <use href='#i-ticket' />
                </svg>
              </span>
              <h3 className='h5 mt-4'>
                Hotel & travel desk
              </h3>
              <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                Block rates at three partner hotels, plus airport transfers on request.
              </p>
              <div className='field mt-5'>
                <label className='sr-only' htmlFor='ht-name'>
                  Name
                </label>
                <input className='input' id='ht-name' name='name' required placeholder='Your name' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='ht-email'>
                  Email
                </label>
                <input className='input' id='ht-email' name='email' type='email' required placeholder='Work email' />
              </div>
              <div className='field mt-3'>
                <label className='sr-only' htmlFor='ht-nights'>
                  Nights
                </label>
                <select className='select' id='ht-nights' name='nights' defaultValue='2 nights'>
                  <option>
                    1 night
                  </option>
                  <option>
                    2 nights
                  </option>
                  <option>
                    3 nights
                  </option>
                  <option>
                    More
                  </option>
                </select>
              </div>
              <button className='btn btn-glass btn-block mt-4' type='submit'>
                Ask for rates
              </button>
            </form>
          </div>
        </div>
      </section>
    </>
  );
}
