/* eslint-disable */
/**
 * SpeakerBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs, then patched by it.
 * The profile's identity (name, designation, portrait, sector chips)
 * comes from src/data/speakers.ts. The narrative below — biography, sessions,
 * publications — is the theme's illustrative copy for the featured profile
 * and is the first thing to replace when real speaker records land.
 * Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';
import type { Speaker } from '@/data/speakers';
import { site } from '@/lib/site';

const SECTOR_NAMES: Record<string, string> = {
  ai: 'Artificial Intelligence',
  health: 'Healthcare',
  edu: 'Education',
  gov: 'Governance',
  city: 'Smart Cities',
  energy: 'Energy',
  bfsi: 'Banking & Fintech',
  pharma: 'Pharma',
};

export default function SpeakerBody({ speaker }: { speaker: Speaker }) {
  const shortName = speaker.name.replace(/,.*$/, '').replace(/^(Shri|Smt|Dr\.?|Prof\.?|Brig\.?)\s+/, '');
  return (
    <>
      <section className='page-head noise' data-parallax-scope=''>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell shell-wide relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/speakers'>
                  Speakers
                </Link>
              </li>
              <li aria-current='page'>
                {shortName}
              </li>
            </ol>
          </nav>
          <div className='grid split' style={{ '--split': 'minmax(0,.72fr) minmax(0,1.28fr)', gap: 'clamp(2rem,4vw,4.5rem)', alignItems: 'center', marginTop: 'var(--sp-6)' } as CSSProperties}>
            <div className='ratio ratio-3-4' style={{ borderRadius: 'var(--r-2xl)', overflow: 'hidden' }} data-reveal='scale'>
              <img src={speaker.image} alt={speaker.name} width='800' height='800' fetchPriority='high' decoding='async' />
            </div>
            <div>
              <div className='flex wrap gap-2'>
                {speaker.badges.map((b) => (
                <span key={b} className={b === 'Government' ? 'tag tag-gov' : 'tag tag-ind'}>
                  {b}
                </span>
                ))}
                {speaker.cats.filter((c) => c !== 'ind').map((c) => (
                <span key={c} className='tag tag-dot' style={{ '--dot': `var(--sector-${c})` } as CSSProperties}>
                  {SECTOR_NAMES[c] ?? c}
                </span>
                ))}
              </div>
              <h1 className='mt-5' data-split=''>
                {speaker.name}
              </h1>
              <p className='lead'>
                {' '}{speaker.role}{speaker.org ? `, ${speaker.org}` : ''}{' '}
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-primary magnetic' href='/videos' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Watch sessions{' '}
                    <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                      <use href='#i-play' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <a className='btn btn-ghost' href='#'>
                  LinkedIn{' '}
                  <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </a>
                {' '}
                <button className='btn btn-soft' data-copy={`${site.url}/speakers/${speaker.slug}`}>
                  Copy profile link
                </button>
              </div>
              <div className='kpi-strip mt-8' data-reveal='up'>
                <div className='kpi'>
                  <b data-count='14'>
                    0
                  </b>
                  <span>
                    Elets appearances
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='9'>
                    0
                  </b>
                  <span>
                    Keynotes delivered
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='6'>
                    0
                  </b>
                  <span>
                    Sectors covered
                  </span>
                </div>
                <div className='kpi'>
                  <b data-count='2016' data-count-plain=''>
                    0
                  </b>
                  <span>
                    First appeared
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-9)' }}>
        <div className='shell shell-wide'>
          <div className='grid split' style={{ '--split': 'minmax(0,1.35fr) minmax(0,.65fr)', gap: 'clamp(2rem,4vw,4.5rem)', alignItems: 'start' } as CSSProperties}>
            <div>
              <span className='eyebrow'>
                Biography
              </span>
              <div className='stack-lg mt-5' style={{ maxWidth: 'var(--maxw-prose)' }}>
                <p className='lead' style={{ color: 'var(--ink-2)' }}>
                  {' '}An officer of the Indian Administrative Service, Akash Tripathi leads two of the institutions that sit closest to India&apos;s citizen-facing digital estate: MyGov, the government&apos;s citizen engagement platform, and Digital India Corporation, the not-for-profit that builds and runs much of the country&apos;s digital public infrastructure.{' '}
                </p>
                <p className='muted'>
                  {' '}His remit spans the practical end of Digital India — platform architecture, adoption across states with very different levels of capacity, and the partnerships with industry that make national-scale rollouts possible. That combination is why he tends to appear on the Elets programme where governance meets engineering rather than in purely policy sessions.{' '}
                </p>
                <p className='muted'>
                  {' '}On our stages he has consistently pressed the same point: platform capability is the easy part. What determines whether a service reaches the last district is institutional readiness — procurement, staffing and the willingness of a department to change how it works.{' '}
                </p>
              </div>
              <div className='rule-fade mt-9 mb-8'></div>
              <span className='eyebrow'>
                Speaking history
              </span>
              <h2 className='h3 mt-4 mb-6'>
                Recent appearances
              </h2>
              <div className='agenda' id='speaker-sessions'>
                <div className='agenda__progress' aria-hidden='true'></div>
                <article className='slot is-open track-ai'>
                  <span className='slot__dot' aria-hidden='true'></span>
                  {' '}
                  <button className='slot__head' aria-expanded='true'>
                    <span className='slot__time'>
                      Jan 2026
                    </span>
                    {' '}
                    <span>
                      <span className='slot__title'>
                        AI in governance: from pilots to production
                      </span>
                      {' '}
                      <span className='slot__tags'>
                        <span className='tag tag-dot'>
                          Keynote
                        </span>
                        <span className='tag'>
                          Elets India AI Summit 2026
                        </span>
                      </span>
                    </span>
                    {' '}
                    <span className='slot__toggle' aria-hidden='true'>
                      <svg width='13' height='13'>
                        <use href='#i-plus' />
                      </svg>
                    </span>
                  </button>
                  <div className='slot__panel'>
                    <div>
                      <div className='slot__body'>
                        <p>
                          Opening keynote at the summit named official pre-event to the India AI Impact Summit. On what separates a departmental pilot from a service citizens actually receive.
                        </p>
                        <Link className='link link-accent mt-4' href='/videos'>
                          Watch the recording{' '}
                          <svg width='14' height='14' aria-hidden='true'>
                            <use href='#i-arrow' />
                          </svg>
                        </Link>
                      </div>
                    </div>
                  </div>
                </article>
                <article className='slot track-gov'>
                  <span className='slot__dot' aria-hidden='true'></span>
                  {' '}
                  <button className='slot__head' aria-expanded='false'>
                    <span className='slot__time'>
                      Jul 2026
                    </span>
                    {' '}
                    <span>
                      <span className='slot__title'>
                        Reshaping the future of India: PSUs in emerging technologies
                      </span>
                      {' '}
                      <span className='slot__tags'>
                        <span className='tag tag-dot'>
                          Panel
                        </span>
                        <span className='tag'>
                          Elets National PSU Summit 2026
                        </span>
                      </span>
                    </span>
                    {' '}
                    <span className='slot__toggle' aria-hidden='true'>
                      <svg width='13' height='13'>
                        <use href='#i-plus' />
                      </svg>
                    </span>
                  </button>
                  <div className='slot__panel'>
                    <div>
                      <div className='slot__body'>
                        <p>
                          Panel on the role of public sector undertakings in emerging technology and national security, part of the summit&apos;s Atma Nirbhar Bharat programme.
                        </p>
                      </div>
                    </div>
                  </div>
                </article>
                <article className='slot track-city'>
                  <span className='slot__dot' aria-hidden='true'></span>
                  {' '}
                  <button className='slot__head' aria-expanded='false'>
                    <span className='slot__time'>
                      May 2026
                    </span>
                    {' '}
                    <span>
                      <span className='slot__title'>
                        Digital public infrastructure and the state
                      </span>
                      {' '}
                      <span className='slot__tags'>
                        <span className='tag tag-dot'>
                          Fireside
                        </span>
                        <span className='tag'>
                          TechMaha Impact 2026
                        </span>
                      </span>
                    </span>
                    {' '}
                    <span className='slot__toggle' aria-hidden='true'>
                      <svg width='13' height='13'>
                        <use href='#i-plus' />
                      </svg>
                    </span>
                  </button>
                  <div className='slot__panel'>
                    <div>
                      <div className='slot__body'>
                        <p>
                          Fireside conversation at the Maharashtra Governance & Tech Summit on what states need centrally, and what they are better off building themselves.
                        </p>
                      </div>
                    </div>
                  </div>
                </article>
                <article className='slot track-edu'>
                  <span className='slot__dot' aria-hidden='true'></span>
                  {' '}
                  <button className='slot__head' aria-expanded='false'>
                    <span className='slot__time'>
                      Jul 2026
                    </span>
                    {' '}
                    <span>
                      <span className='slot__title'>
                        Digital infrastructure for skilling at scale
                      </span>
                      {' '}
                      <span className='slot__tags'>
                        <span className='tag tag-dot'>
                          Keynote
                        </span>
                        <span className='tag'>
                          3rd National Digital Innovation Summit, Lucknow
                        </span>
                      </span>
                    </span>
                    {' '}
                    <span className='slot__toggle' aria-hidden='true'>
                      <svg width='13' height='13'>
                        <use href='#i-plus' />
                      </svg>
                    </span>
                  </button>
                  <div className='slot__panel'>
                    <div>
                      <div className='slot__body'>
                        <p>
                          Delivered at the Uttar Pradesh summit that spotlighted the state&apos;s AI, innovation and digital infrastructure agenda.
                        </p>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </div>
            <aside className='side-sticky stack-lg'>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  At a glance
                </h3>
                <dl className='mt-4' style={{ display: 'grid', gap: '.85rem', fontSize: 'var(--fs-sm)' }}>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Service
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        IAS
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Ministry
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        MeitY
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Based in
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        New Delhi
                      </strong>
                    </dd>
                  </div>
                  <div className='flex between gap-3'>
                    <dt className='muted'>
                      Topics
                    </dt>
                    <dd className='text-right'>
                      <strong>
                        DPI · AI · Governance
                      </strong>
                    </dd>
                  </div>
                </dl>
              </div>
              <div>
                <h3 className='h5 mb-4'>
                  Publications & articles
                </h3>
                <Link className='news news--row' href='/news'>
                  <span className='news__media'>
                    <img src='/assets/img/events/ev-10.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                  </span>
                  {' '}
                  <span>
                    <span className='news__meta'>
                      <span>
                        eGov
                      </span>
                    </span>
                    <h3>
                      The AI-ready state: what readiness actually means
                    </h3>
                  </span>
                </Link>
                {' '}
                <Link className='news news--row' href='/news'>
                  <span className='news__media'>
                    <img src='/assets/img/events/ev-05.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                  </span>
                  {' '}
                  <span>
                    <span className='news__meta'>
                      <span>
                        eGov
                      </span>
                    </span>
                    <h3>
                      Platforms are easy. Adoption is the work.
                    </h3>
                  </span>
                </Link>
                {' '}
                <Link className='news news--row' href='/news'>
                  <span className='news__media'>
                    <img src='/assets/img/events/ev-11.svg' alt='' width='1600' height='1000' loading='lazy' decoding='async' />
                  </span>
                  {' '}
                  <span>
                    <span className='news__meta'>
                      <span>
                        digitalLEARNING
                      </span>
                    </span>
                    <h3>
                      Skilling infrastructure for a billion learners
                    </h3>
                  </span>
                </Link>
              </div>
              <div className='card' style={{ padding: 'var(--sp-5)' }}>
                <h3 className='h5'>
                  Invite to speak
                </h3>
                <p className='muted mt-3' style={{ fontSize: 'var(--fs-sm)' }}>
                  Speaking requests are handled by the programme secretariat, not by speakers directly.
                </p>
                <Link className='btn btn-primary btn-block mt-4' href='/contact'>
                  Contact the secretariat
                </Link>
              </div>
            </aside>
          </div>
        </div>
      </section>
      <section className='band-dark noise section'>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                On video
              </span>
              <h2 data-split=''>
                Sessions & keynotes
              </h2>
            </div>
            <div className='sec-head__aside'>
              <Link className='btn btn-glass' href='/videos'>
                Full library{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </Link>
            </div>
          </div>
          <div className='vid-row' role='list'>
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-01.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              <span className='video__dur'>
                42:16
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              <span className='video__meta'>
                <h3>
                  AI in governance: pilots to production
                </h3>
                <p>
                  India AI Summit 2026
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-08.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              <span className='video__dur'>
                29:12
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              <span className='video__meta'>
                <h3>
                  The ONDC effect
                </h3>
                <p>
                  World Fintech Summit
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-06.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              <span className='video__dur'>
                45:20
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              <span className='video__meta'>
                <h3>
                  Public sector cybersecurity
                </h3>
                <p>
                  Public Sector Day, Delhi
                </p>
              </span>
            </a>
            {' '}
            <a className='video' role='listitem' href='#video-modal' data-modal-open='video-modal' data-cursor='Play'>
              <img src='/assets/img/videos/vid-05.svg' alt='' width='1600' height='900' loading='lazy' decoding='async' />
              <span className='video__dur'>
                24:39
              </span>
              <span className='video__play'>
                <i>
                  <svg width='18' height='18' aria-hidden='true'>
                    <use href='#i-play' />
                  </svg>
                </i>
              </span>
              <span className='video__meta'>
                <h3>
                  Campus to career
                </h3>
                <p>
                  Campus to Career Summit
                </p>
              </span>
            </a>
          </div>
        </div>
      </section>
      <section className='section'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                From the floor
              </span>
              <h2 data-split=''>
                Photographs
              </h2>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <Link href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
              <img src='/assets/img/gallery/g-01.svg' alt='Plenary session' width='1200' height='900' loading='lazy' decoding='async' />
            </Link>
            {' '}
            <Link href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
              <img src='/assets/img/gallery/g-04.svg' alt='Roundtable' width='1200' height='900' loading='lazy' decoding='async' />
            </Link>
            {' '}
            <Link href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
              <img src='/assets/img/gallery/g-06.svg' alt='Networking' width='1200' height='900' loading='lazy' decoding='async' />
            </Link>
            {' '}
            <Link href='/gallery' data-reveal='up' style={{ borderRadius: 'var(--r-md)', overflow: 'hidden', display: 'block' }}>
              <img src='/assets/img/gallery/g-09.svg' alt='Fireside chat' width='1200' height='900' loading='lazy' decoding='async' />
            </Link>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Also on the programme
              </span>
              <h2 data-split=''>
                Related speakers
              </h2>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <article className='speaker' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-08.svg' alt='Dr. Rajendra Kumar, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/rajendra-kumar' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/rajendra-kumar' data-cursor='Profile'>
                    Dr. Rajendra Kumar, IAS
                  </Link>
                </h3>
                <p>
                  Secretary
                  <br />
                  <span className='dim'>
                    Ministry of Home Affairs
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-05.svg' alt='Thampy Koshy' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/thampy-koshy' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/thampy-koshy' data-cursor='Profile'>
                    Thampy Koshy
                  </Link>
                </h3>
                <p>
                  MD & CEO
                  <br />
                  <span className='dim'>
                    Open Network for Digital Commerce
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-11.svg' alt='Deepak Bagla' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/deepak-bagla' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/deepak-bagla' data-cursor='Profile'>
                    Deepak Bagla
                  </Link>
                </h3>
                <p>
                  Mission Director, Atal Innovation Mission
                  <br />
                  <span className='dim'>
                    NITI Aayog
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                <img src='/assets/img/speakers/sp-13.svg' alt='Dr. Shailesh Kumar' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/shailesh-kumar' aria-label='Profile'>
                      <svg width='14' height='14'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/shailesh-kumar' data-cursor='Profile'>
                    Dr. Shailesh Kumar
                  </Link>
                </h3>
                <p>
                  Chief Data Scientist, CoE AI/ML
                  <br />
                  <span className='dim'>
                    Jio
                  </span>
                </p>
              </div>
            </article>
          </div>
        </div>
      </section>
      <div className='modal modal--video' id='video-modal' role='dialog' aria-modal='true' aria-label='Session video' aria-hidden='true'>
        <div className='modal__scrim'></div>
        <div className='modal__card'>
          <button className='modal__close' data-modal-close='' aria-label='Close video'>
            <svg width='15' height='15'>
              <use href='#i-x' />
            </svg>
          </button>
          <div className='ratio ratio-16-9' style={{ background: '#000' }}>
            <div style={{ display: 'grid', placeItems: 'center', height: '100%', color: 'rgba(255,255,255,.5)', textAlign: 'center', padding: '2rem' }}>
              <div>
                <svg width='38' height='38' aria-hidden='true'>
                  <use href='#i-play' />
                </svg>
                <p className='mono mt-4'>
                  Drop your player embed here
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
