/* eslint-disable */
/**
 * SpeakersBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function SpeakersBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li aria-current='page'>
                Speakers
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            The people who set{' '}
            <em className='serif-i grad-text'>
              the agenda
            </em>
          </h1>
          <p className='lead'>
            {' '}Over twenty thousand speakers have taken an Elets stage since 2003 — secretaries and IAS officers, hospital and university chiefs, bank CTOs and chief data scientists. This is a selection from the current season.{' '}
          </p>
          <div className='grid mt-8 split' style={{ '--split': 'minmax(0,1fr) auto', gap: 'var(--sp-4)', alignItems: 'center' } as CSSProperties}>
            <div className='search'>
              <svg width='16' height='16' aria-hidden='true'>
                <use href='#i-search' />
              </svg>
              {' '}
              <label className='sr-only' htmlFor='sp-search'>
                Search speakers
              </label>
              {' '}
              <input className='input' id='sp-search' type='search' placeholder='Search by name, designation or organisation…' data-search='#speaker-grid' />
            </div>
            <Link className='btn btn-primary magnetic' href='/registration#speaking' data-magnet='0.2'>
              <span className='magnetic__inner'>
                Nominate a speaker{' '}
                <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </span>
            </Link>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-6)' }}>
        <div className='shell shell-wide'>
          <div className='flex between center wrap gap-4 mb-8'>
            <div className='filters' data-filters='#speaker-grid' role='group' aria-label='Filter speakers'>
              <span className='filters__pill' aria-hidden='true'></span>
              {' '}
              <button data-filter='all' aria-pressed='true'>
                Everyone
              </button>
              {' '}
              <button data-filter='gov' aria-pressed='false'>
                Government
              </button>
              {' '}
              <button data-filter='ind' aria-pressed='false'>
                Industry
              </button>
              {' '}
              <button data-filter='ai' aria-pressed='false'>
                AI
              </button>
              {' '}
              <button data-filter='health' aria-pressed='false'>
                Health
              </button>
              {' '}
              <button data-filter='energy' aria-pressed='false'>
                Energy
              </button>
              {' '}
              <button data-filter='city' aria-pressed='false'>
                Cities
              </button>
              {' '}
              <button data-filter='bfsi' aria-pressed='false'>
                BFSI
              </button>
            </div>
            <p className='mono muted'>
              16 of 20,000+ shown
            </p>
          </div>
          <div className='grid g-4' id='speaker-grid' data-reveal-group='' role='list' aria-live='polite'>
            <article className='speaker' role='listitem' data-cat='gov energy' data-search-text={"Brig. B. D. Mishra Hon'ble Lieutenant Governor UT Administration Ladakh"} data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-01.svg' alt='Brig. B. D. Mishra' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/b-d-mishra' aria-label='Profile of Brig. B. D. Mishra'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/b-d-mishra' data-cursor='Profile'>
                    Brig. B. D. Mishra
                  </Link>
                </h3>
                <p>
                  Hon&apos;ble Lieutenant Governor
                  <br />
                  <span className='dim'>
                    UT Administration Ladakh
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov city' data-search-text='Amit Sharma, IAS Secretary (IT, Transport, RD, S&T) & MD SIDCO UT Administration Ladakh' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-02.svg' alt='Amit Sharma, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/amit-sharma' aria-label='Profile of Amit Sharma, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/amit-sharma' data-cursor='Profile'>
                    Amit Sharma, IAS
                  </Link>
                </h3>
                <p>
                  Secretary (IT, Transport, RD, S&T) & MD SIDCO
                  <br />
                  <span className='dim'>
                    UT Administration Ladakh
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov energy' data-search-text='Gaurav Gupta, IAS Additional Chief Secretary, Energy Government of Karnataka' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-03.svg' alt='Gaurav Gupta, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/gaurav-gupta' aria-label='Profile of Gaurav Gupta, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/gaurav-gupta' data-cursor='Profile'>
                    Gaurav Gupta, IAS
                  </Link>
                </h3>
                <p>
                  Additional Chief Secretary, Energy
                  <br />
                  <span className='dim'>
                    Government of Karnataka
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov ai' data-search-text='Shri Akash Tripathi, IAS CEO MyGov · MD & CEO, Digital India Corporation MeitY, Government of India' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-04.svg' alt='Shri Akash Tripathi, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/akash-tripathi' aria-label='Profile of Shri Akash Tripathi, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/akash-tripathi' data-cursor='Profile'>
                    Shri Akash Tripathi, IAS
                  </Link>
                </h3>
                <p>
                  CEO MyGov · MD & CEO, Digital India Corporation
                  <br />
                  <span className='dim'>
                    MeitY, Government of India
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind bfsi' data-search-text='Thampy Koshy Managing Director & CEO Open Network for Digital Commerce (ONDC)' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-05.svg' alt='Thampy Koshy' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/thampy-koshy' aria-label='Profile of Thampy Koshy'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/thampy-koshy' data-cursor='Profile'>
                    Thampy Koshy
                  </Link>
                </h3>
                <p>
                  Managing Director & CEO
                  <br />
                  <span className='dim'>
                    Open Network for Digital Commerce (ONDC)
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov' data-search-text='Meeta R Lochan, IAS Secretary, NCBC Ministry of Social Justice & Empowerment' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-06.svg' alt='Meeta R Lochan, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/meeta-r-lochan' aria-label='Profile of Meeta R Lochan, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/meeta-r-lochan' data-cursor='Profile'>
                    Meeta R Lochan, IAS
                  </Link>
                </h3>
                <p>
                  Secretary, NCBC
                  <br />
                  <span className='dim'>
                    Ministry of Social Justice & Empowerment
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov health' data-search-text='Rajit Punhani, IAS Chief Executive Officer Food Safety and Standards Authority of India' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-07.svg' alt='Rajit Punhani, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/rajit-punhani' aria-label='Profile of Rajit Punhani, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/rajit-punhani' data-cursor='Profile'>
                    Rajit Punhani, IAS
                  </Link>
                </h3>
                <p>
                  Chief Executive Officer
                  <br />
                  <span className='dim'>
                    Food Safety and Standards Authority of India
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov ai' data-search-text='Dr. Rajendra Kumar, IAS Secretary Ministry of Home Affairs' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-08.svg' alt='Dr. Rajendra Kumar, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/rajendra-kumar' aria-label='Profile of Dr. Rajendra Kumar, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/rajendra-kumar' data-cursor='Profile'>
                    Dr. Rajendra Kumar, IAS
                  </Link>
                </h3>
                <p>
                  Secretary
                  <br />
                  <span className='dim'>
                    Ministry of Home Affairs
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov energy' data-search-text='Ashok K.K. Meena Secretary, Drinking Water & Sanitation Ministry of Jal Shakti' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-09.svg' alt='Ashok K.K. Meena' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/ashok-k-k-meena' aria-label='Profile of Ashok K.K. Meena'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/ashok-k-k-meena' data-cursor='Profile'>
                    Ashok K.K. Meena
                  </Link>
                </h3>
                <p>
                  Secretary, Drinking Water & Sanitation
                  <br />
                  <span className='dim'>
                    Ministry of Jal Shakti
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov city' data-search-text='D Thara, IAS Additional Secretary Ministry of Housing and Urban Affairs' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-10.svg' alt='D Thara, IAS' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/d-thara' aria-label='Profile of D Thara, IAS'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/d-thara' data-cursor='Profile'>
                    D Thara, IAS
                  </Link>
                </h3>
                <p>
                  Additional Secretary
                  <br />
                  <span className='dim'>
                    Ministry of Housing and Urban Affairs
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='gov ai' data-search-text='Deepak Bagla Mission Director, Atal Innovation Mission NITI Aayog' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-gov'>
                    Government
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-11.svg' alt='Deepak Bagla' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/deepak-bagla' aria-label='Profile of Deepak Bagla'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/deepak-bagla' data-cursor='Profile'>
                    Deepak Bagla
                  </Link>
                </h3>
                <p>
                  Mission Director, Atal Innovation Mission
                  <br />
                  <span className='dim'>
                    NITI Aayog
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind energy' data-search-text='Himanshu Pant Chief Digital Officer Adani Group' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-12.svg' alt='Himanshu Pant' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/himanshu-pant' aria-label='Profile of Himanshu Pant'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/himanshu-pant' data-cursor='Profile'>
                    Himanshu Pant
                  </Link>
                </h3>
                <p>
                  Chief Digital Officer
                  <br />
                  <span className='dim'>
                    Adani Group
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind ai' data-search-text='Dr. Shailesh Kumar Chief Data Scientist, CoE AI/ML Jio' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-13.svg' alt='Dr. Shailesh Kumar' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/shailesh-kumar' aria-label='Profile of Dr. Shailesh Kumar'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/shailesh-kumar' data-cursor='Profile'>
                    Dr. Shailesh Kumar
                  </Link>
                </h3>
                <p>
                  Chief Data Scientist, CoE AI/ML
                  <br />
                  <span className='dim'>
                    Jio
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind ai' data-search-text='Gaurav Duggal SVP & Head of Data Analytics & AI Jio Platforms Limited' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-14.svg' alt='Gaurav Duggal' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/gaurav-duggal' aria-label='Profile of Gaurav Duggal'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/gaurav-duggal' data-cursor='Profile'>
                    Gaurav Duggal
                  </Link>
                </h3>
                <p>
                  SVP & Head of Data Analytics & AI
                  <br />
                  <span className='dim'>
                    Jio Platforms Limited
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind bfsi' data-search-text='Deepak Gupta Group Chief Technology Officer CARS24' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-15.svg' alt='Deepak Gupta' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/deepak-gupta' aria-label='Profile of Deepak Gupta'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/deepak-gupta' data-cursor='Profile'>
                    Deepak Gupta
                  </Link>
                </h3>
                <p>
                  Group Chief Technology Officer
                  <br />
                  <span className='dim'>
                    CARS24
                  </span>
                </p>
              </div>
            </article>
            <article className='speaker' role='listitem' data-cat='ind' data-search-text='Dr Ravi Gupta Founder, CEO & Editor-in-Chief Elets Technomedia' data-reveal='up'>
              <div className='speaker__media'>
                <span className='speaker__badges'>
                  <span className='tag tag-ind'>
                    Industry
                  </span>
                </span>
                {' '}
                <img src='/assets/img/speakers/sp-16.svg' alt='Dr Ravi Gupta' width='800' height='800' loading='lazy' decoding='async' />
                <div className='speaker__veil'>
                  <div className='speaker__socials'>
                    <Link href='/speakers/ravi-gupta' aria-label='Profile of Dr Ravi Gupta'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-arrow' />
                      </svg>
                    </Link>
                    {' '}
                    <a href='#' aria-label='LinkedIn'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-in' />
                      </svg>
                    </a>
                    {' '}
                    <Link href='/videos' aria-label='Sessions'>
                      <svg width='14' height='14' aria-hidden='true'>
                        <use href='#i-play' />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
              <div className='speaker__info'>
                <h3>
                  <Link href='/speakers/ravi-gupta' data-cursor='Profile'>
                    Dr Ravi Gupta
                  </Link>
                </h3>
                <p>
                  Founder, CEO & Editor-in-Chief
                  <br />
                  <span className='dim'>
                    Elets Technomedia
                  </span>
                </p>
              </div>
            </article>
          </div>
          <p className='empty hide mt-6' data-empty=''>
            No speakers match that search.
          </p>
          <nav className='pager mt-9' aria-label='Pagination'>
            <a href='#' aria-label='Previous page'>
              <svg width='15' height='15' style={{ transform: 'rotate(180deg)' }} aria-hidden='true'>
                <use href='#i-arrow-r' />
              </svg>
            </a>
            {' '}
            <a href='#' aria-current='page'>
              1
            </a>
            {' '}
            <a href='#'>
              2
            </a>
            {' '}
            <a href='#'>
              3
            </a>
            {' '}
            <span aria-hidden='true'>
              …
            </span>
            {' '}
            <a href='#'>
              48
            </a>
            {' '}
            <a href='#' aria-label='Next page'>
              <svg width='15' height='15' aria-hidden='true'>
                <use href='#i-arrow-r' />
              </svg>
            </a>
          </nav>
        </div>
      </section>
      <section className='band-dark noise section'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell relative'>
          <div className='grid split' style={{ '--split': 'minmax(0,.8fr) minmax(0,1.2fr)', gap: 'clamp(2rem,4vw,4.5rem)', alignItems: 'center' } as CSSProperties}>
            <div className='ratio ratio-3-4' style={{ borderRadius: 'var(--r-2xl)', overflow: 'hidden' }} data-reveal='scale'>
              <img src='/assets/img/speakers/sp-04.svg' alt='Shri Akash Tripathi, IAS' width='800' height='800' loading='lazy' decoding='async' />
            </div>
            <div>
              <span className='eyebrow'>
                Speaker spotlight
              </span>
              <h2 className='h2 mt-5' data-split=''>
                “Digital public infrastructure only counts when the last district can use it.”
              </h2>
              <p className='lead mt-5'>
                {' '}Shri Akash Tripathi, IAS — CEO MyGov and MD & CEO of Digital India Corporation at MeitY — has spoken across our governance and AI programmes.{' '}
              </p>
              <p className='mono dim mt-3'>
                Quotation shown is placeholder copy for design review.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand' href='/speakers/akash-tripathi'>
                  Read the full profile{' '}
                  <svg className='btn__icon' width='14' height='14' aria-hidden='true'>
                    <use href='#i-arrow' />
                  </svg>
                </Link>
                {' '}
                <Link className='btn btn-glass' href='/videos'>
                  Watch the session
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className='section-sm'>
        <div className='shell'>
          <div className='cta noise' data-reveal='scale'>
            <div className='aurora' aria-hidden='true'>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className='relative'>
              <span className='eyebrow' style={{ color: 'rgba(255,255,255,.55)' }}>
                Programme committee
              </span>
              <h2 className='mt-5' data-split=''>
                Have something worth an hour of this room&apos;s time?
              </h2>
              <p>
                Submissions are reviewed fortnightly. Tell us the argument, not the product.
              </p>
              <div className='flex wrap gap-3 mt-8'>
                <Link className='btn btn-brand btn-lg magnetic' href='/registration#speaking' data-magnet='0.2'>
                  <span className='magnetic__inner'>
                    Submit to speak{' '}
                    <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                      <use href='#i-arrow' />
                    </svg>
                  </span>
                </Link>
                {' '}
                <Link className='btn btn-glass btn-lg' href='/contact'>
                  Talk to the secretariat
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
