/* eslint-disable */
/**
 * SponsorsBody — ported from the Elets HTML theme.
 * Generated by tools/html-to-jsx.mjs. Edit the theme source or this file,
 * but do not re-run the generator over hand-edits without checking git.
 */
import type { CSSProperties } from 'react';
import Link from 'next/link';

export default function SponsorsBody() {
  return (
    <>
      <section className='page-head noise'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='grid-lines' aria-hidden='true'></div>
        <div className='shell relative'>
          <nav aria-label='Breadcrumb'>
            <ol className='crumbs'>
              <li>
                <Link href='/'>
                  Home
                </Link>
              </li>
              <li aria-current='page'>
                Sponsors & partners
              </li>
            </ol>
          </nav>
          <h1 data-split=''>
            Put your brand in a room that{' '}
            <em className='serif-i grad-text'>
              decides things
            </em>
          </h1>
          <p className='lead'>
            {' '}Elets audiences are weighted toward people who sign off on procurement — secretaries, utility chairs, hospital CIOs, bank CTOs. Partnership buys access to that room and to the media around it, not a logo on a banner.{' '}
          </p>
          <div className='flex wrap gap-3 mt-8'>
            <a className='btn btn-primary btn-lg magnetic' href='#enquire' data-magnet='0.2'>
              <span className='magnetic__inner'>
                Request the deck{' '}
                <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </span>
            </a>
            {' '}
            <a className='btn btn-ghost btn-lg' href='#tiers'>
              See the tiers
            </a>
          </div>
        </div>
      </section>
      <section className='section' style={{ paddingTop: 'var(--sp-8)' }}>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                This season
              </span>
              <h2 data-split=''>
                Current partners
              </h2>
            </div>
          </div>
          <p className='mono muted mb-4'>
            Presenting partner
          </p>
          <a className='card card--glow mb-8' href='#enquire' data-reveal='up' style={{ flexDirection: 'row', alignItems: 'center', gap: 'clamp(1.5rem,4vw,4rem)', padding: 'clamp(1.75rem,4vw,3rem)', flexWrap: 'wrap' }}>
            <img src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' style={{ height: '46px', width: 'auto', filter: 'var(--logo-filter)', opacity: '.9' }} loading='lazy' decoding='async' />
            {' '}
            <span style={{ flex: '1', minWidth: '260px' }}>
              <strong style={{ display: 'block', fontSize: 'var(--fs-md)', letterSpacing: 'var(--tracking-tight)' }}>
                Presenting partner, 2026 season
              </strong>
              {' '}
              <span className='muted' style={{ fontSize: 'var(--fs-sm)' }}>
                Title billing across every asset, a keynote slot on the main stage, and a co-hosted closed-door roundtable. One per event.
              </span>
            </span>
            {' '}
            <span className='go' aria-hidden='true'>
              <svg width='15' height='15'>
                <use href='#i-arrow' />
              </svg>
            </span>
          </a>
          <p className='mono muted mb-4'>
            Platform & gold partners
          </p>
          <div className='grid g-4 mb-8' data-reveal-group=''>
            <a className='card' href='#enquire' data-reveal='up' style={{ alignItems: 'center', justifyContent: 'center', padding: 'var(--sp-7) var(--sp-5)' }}>
              <img src='/assets/img/partners/p-02.svg' alt='Confluent' width='220' height='48' style={{ height: '32px', width: 'auto', filter: 'var(--logo-filter)', opacity: '.78' }} loading='lazy' decoding='async' />
            </a>
            {' '}
            <a className='card' href='#enquire' data-reveal='up' style={{ alignItems: 'center', justifyContent: 'center', padding: 'var(--sp-7) var(--sp-5)' }}>
              <img src='/assets/img/partners/p-03.svg' alt='Infinity Labs' width='220' height='48' style={{ height: '32px', width: 'auto', filter: 'var(--logo-filter)', opacity: '.78' }} loading='lazy' decoding='async' />
            </a>
            {' '}
            <a className='card' href='#enquire' data-reveal='up' style={{ alignItems: 'center', justifyContent: 'center', padding: 'var(--sp-7) var(--sp-5)' }}>
              <img src='/assets/img/partners/p-04.svg' alt='ESDS' width='220' height='48' style={{ height: '32px', width: 'auto', filter: 'var(--logo-filter)', opacity: '.78' }} loading='lazy' decoding='async' />
            </a>
            {' '}
            <a className='card' href='#enquire' data-reveal='up' style={{ alignItems: 'center', justifyContent: 'center', padding: 'var(--sp-7) var(--sp-5)' }}>
              <img src='/assets/img/partners/p-05.svg' alt='Karix' width='220' height='48' style={{ height: '32px', width: 'auto', filter: 'var(--logo-filter)', opacity: '.78' }} loading='lazy' decoding='async' />
            </a>
          </div>
          <p className='mono muted mb-4'>
            Exhibitors & supporting partners
          </p>
          <div className='marquee' style={{ '--marquee-dur': '40s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-06.svg' alt='Chat360' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-04.svg' alt='ESDS' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-05.svg' alt='Karix' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-01.svg' alt='NxtGen' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-02.svg' alt='Confluent' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-03.svg' alt='Infinity Labs' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
          <p className='mono muted mb-4 mt-8'>
            Institutions represented on our stages
          </p>
          <div className='marquee marquee--reverse' style={{ '--marquee-dur': '48s' } as CSSProperties}>
            <div className='marquee__track'>
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-07.svg' alt='Digital India' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-08.svg' alt='MyGov' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-09.svg' alt='ONDC' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-10.svg' alt='NITI Aayog' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-11.svg' alt='MeitY' width='220' height='48' loading='lazy' decoding='async' />
              </span>
              {' '}
              <span className='marquee__item'>
                <img src='/assets/img/partners/p-12.svg' alt='FSSAI' width='220' height='48' loading='lazy' decoding='async' />
              </span>
            </div>
          </div>
          <p className='mono dim mt-4'>
            Listing indicates participation on our programmes; it does not imply endorsement or commercial partnership.
          </p>
        </div>
      </section>
      <section className='band-dark noise section'>
        <div className='aurora' aria-hidden='true'>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className='shell shell-wide relative'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Why partners come back
              </span>
              <h2 data-split=''>
                The audience you are actually buying
              </h2>
            </div>
          </div>
          <div className='grid g-4 mb-9' data-reveal-group=''>
            <div className='stat' data-reveal='up'>
              <b data-count='1000' data-count-suf='+'>
                0
              </b>
              <span>
                Conferences convened since 2003
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='600000' data-count-suf='+'>
                0
              </b>
              <span>
                Delegates through the doors
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='4' data-count-suf='M+'>
                0
              </b>
              <span>
                Monthly readers across four magazines
              </span>
            </div>
            <div className='stat' data-reveal='up'>
              <b data-count='10' data-count-suf='M+'>
                0
              </b>
              <span>
                Views on published session video
              </span>
            </div>
          </div>
          <div className='grid g-2' style={{ gap: 'clamp(2rem,4vw,4rem)' }}>
            <div>
              <h3 className='h4 mb-5'>
                Seniority of the room
              </h3>
              <div style={{ display: 'grid', gap: '1.35rem' }}>
                <div>
                  <div className='flex between'>
                    <span style={{ fontSize: 'var(--fs-sm)' }}>
                      Secretary / CXO / Board
                    </span>
                    <span className='mono muted'>
                      38%
                    </span>
                  </div>
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar='38'></span>
                  </span>
                </div>
                <div>
                  <div className='flex between'>
                    <span style={{ fontSize: 'var(--fs-sm)' }}>
                      Director / Head of function
                    </span>
                    <span className='mono muted'>
                      34%
                    </span>
                  </div>
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar='34'></span>
                  </span>
                </div>
                <div>
                  <div className='flex between'>
                    <span style={{ fontSize: 'var(--fs-sm)' }}>
                      Senior manager
                    </span>
                    <span className='mono muted'>
                      20%
                    </span>
                  </div>
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar='20'></span>
                  </span>
                </div>
                <div>
                  <div className='flex between'>
                    <span style={{ fontSize: 'var(--fs-sm)' }}>
                      Analyst / other
                    </span>
                    <span className='mono muted'>
                      8%
                    </span>
                  </div>
                  <span className='seats__bar'>
                    <span className='seats__fill' data-bar='8'></span>
                  </span>
                </div>
              </div>
            </div>
            <div>
              <h3 className='h4 mb-5'>
                What a partnership actually gets you
              </h3>
              <ul style={{ display: 'grid', gap: '.9rem' }}>
                <li className='flex gap-3'>
                  <svg width='17' height='17' style={{ color: 'var(--saffron-400)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  <span>
                    A speaking slot on the record — not a sponsored break
                  </span>
                </li>
                <li className='flex gap-3'>
                  <svg width='17' height='17' style={{ color: 'var(--saffron-400)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  <span>
                    Introductions made by the programme team, by name, on the day
                  </span>
                </li>
                <li className='flex gap-3'>
                  <svg width='17' height='17' style={{ color: 'var(--saffron-400)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  <span>
                    An interview or feature in the relevant Elets magazine
                  </span>
                </li>
                <li className='flex gap-3'>
                  <svg width='17' height='17' style={{ color: 'var(--saffron-400)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  <span>
                    Your session in the video library, where it keeps earning views
                  </span>
                </li>
                <li className='flex gap-3'>
                  <svg width='17' height='17' style={{ color: 'var(--saffron-400)', flex: 'none', marginTop: '3px' }} aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  <span>
                    The delegate list, for opted-in attendees only
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className='section' id='tiers'>
        <div className='shell shell-wide'>
          <div className='sec-head'>
            <div>
              <span className='sec-head__kicker mono'>
                Packages
              </span>
              <h2 data-split=''>
                Five tiers, one conversation
              </h2>
              <p>
                Indicative for a single national summit. Multi-event and annual programmes are quoted separately.
              </p>
            </div>
          </div>
          <div className='grid g-4' data-reveal-group=''>
            <div className='price' data-reveal='up'>
              <span className='tag' style={{ alignSelf: 'start' }}>
                Supporting
              </span>
              <h3 className='h4'>
                Supporting partner
              </h3>
              <div className='price__amt'>
                <b>
                  ₹3.5L
                </b>
                <span>
                  from
                </span>
              </div>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Logo on all event collateral
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}2 delegate passes
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Delegate bag insert
                </li>
              </ul>
              <a className='btn btn-soft btn-block mt-4' href='#enquire'>
                Enquire
              </a>
            </div>
            <div className='price' data-reveal='up'>
              <span className='tag' style={{ alignSelf: 'start', color: '#9aa0aa' }}>
                Silver
              </span>
              <h3 className='h4'>
                Silver partner
              </h3>
              <div className='price__amt'>
                <b>
                  ₹7L
                </b>
                <span>
                  from
                </span>
              </div>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Everything in Supporting
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Exhibition stand (3×2m)
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}5 delegate passes
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Panel seat
                </li>
              </ul>
              <a className='btn btn-soft btn-block mt-4' href='#enquire'>
                Enquire
              </a>
            </div>
            <div className='price price--featured' data-reveal='up'>
              <span className='tag tag-solid' style={{ alignSelf: 'start' }}>
                Gold · most chosen
              </span>
              <h3 className='h4'>
                Gold partner
              </h3>
              <div className='price__amt'>
                <b>
                  ₹14L
                </b>
                <span>
                  from
                </span>
              </div>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Everything in Silver
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Exhibition stand (6×3m)
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}12 delegate passes
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}20-minute session slot
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Magazine feature
                </li>
              </ul>
              <a className='btn btn-brand btn-block mt-4' href='#enquire'>
                Enquire
              </a>
            </div>
            <div className='price' data-reveal='up'>
              <span className='tag' style={{ alignSelf: 'start', color: 'var(--saffron-500)' }}>
                Presenting
              </span>
              <h3 className='h4'>
                Presenting partner
              </h3>
              <div className='price__amt'>
                <b>
                  On request
                </b>
                <span>
                  one per event
                </span>
              </div>
              <ul>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Title billing on all assets
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Keynote slot on the main stage
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}25 delegate passes
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Co-hosted closed-door roundtable
                </li>
                <li>
                  <svg width='15' height='15' aria-hidden='true'>
                    <use href='#i-check' />
                  </svg>
                  {' '}Year-round media placement
                </li>
              </ul>
              <a className='btn btn-soft btn-block mt-4' href='#enquire'>
                Talk to us
              </a>
            </div>
          </div>
          <p className='mono dim mt-6'>
            Rates are indicative and vary by event size and city. GST additional. Government and academic institutions partner at cost.
          </p>
        </div>
      </section>
      <section className='section' style={{ paddingTop: '0' }}>
        <div className='shell'>
          <div className='grid g-3' data-reveal-group=''>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “We booked two hospital deployments off conversations that started at the Healthcare Innovation Summit.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-15.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                <span>
                  <b>
                    Chief Technology Officer
                  </b>
                  <span>
                    Health-tech platform · Gold partner
                  </span>
                </span>
              </figcaption>
            </figure>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “The stand paid for itself before lunch on day one. It is the only Indian event where that is reliably true for us.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-14.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                <span>
                  <b>
                    VP Marketing
                  </b>
                  <span>
                    Cloud infrastructure vendor · Exhibitor
                  </span>
                </span>
              </figcaption>
            </figure>
            <figure className='quote' data-reveal='up'>
              <blockquote>
                “What we valued was the magazine feature afterwards. The event ends; the article keeps working.”
              </blockquote>
              <figcaption>
                <img src='/assets/img/speakers/sp-16.svg' alt='' width='44' height='44' loading='lazy' decoding='async' />
                <span>
                  <b>
                    Head of Public Sector
                  </b>
                  <span>
                    Systems integrator · Presenting partner
                  </span>
                </span>
              </figcaption>
            </figure>
          </div>
          <p className='mono dim text-center mt-6'>
            Quotations shown are placeholder copy for design review.
          </p>
        </div>
      </section>
      <section className='section' id='enquire' style={{ paddingTop: '0' }}>
        <div className='shell shell-narrow'>
          <div className='card' style={{ padding: 'clamp(1.5rem,4vw,3.5rem)' }}>
            <span className='eyebrow'>
              Partnerships
            </span>
            <h2 className='h3 mt-4'>
              Tell us who you want in the room
            </h2>
            <p className='muted mt-3' style={{ maxWidth: '56ch' }}>
              We will come back with the events where that audience actually shows up, the tier that fits, and the deck. Usually within one working day.
            </p>
            <form className='mt-8' data-demo='Thanks — the partnerships team will be in touch within one working day.'>
              <div className='field-row'>
                <div className='field'>
                  <label htmlFor='pn'>
                    Your name{' '}
                    <span className='req'>
                      *
                    </span>
                  </label>
                  <input className='input' id='pn' name='name' required autoComplete='name' />
                </div>
                <div className='field'>
                  <label htmlFor='pe'>
                    Work email{' '}
                    <span className='req'>
                      *
                    </span>
                  </label>
                  <input className='input' id='pe' name='email' type='email' required autoComplete='email' />
                </div>
              </div>
              <div className='field-row mt-5'>
                <div className='field'>
                  <label htmlFor='po'>
                    Organisation{' '}
                    <span className='req'>
                      *
                    </span>
                  </label>
                  <input className='input' id='po' name='org' required autoComplete='organization' />
                </div>
                <div className='field'>
                  <label htmlFor='pp'>
                    Phone
                  </label>
                  <input className='input' id='pp' name='phone' type='tel' autoComplete='tel' />
                </div>
              </div>
              <div className='field-row mt-5'>
                <div className='field'>
                  <label htmlFor='ps'>
                    Sector of interest
                  </label>
                  <select className='select' id='ps' name='sector'>
                    <option>
                      Governance & PSU
                    </option>
                    <option>
                      Healthcare
                    </option>
                    <option>
                      Education & skilling
                    </option>
                    <option>
                      Banking & fintech
                    </option>
                    <option>
                      Artificial intelligence
                    </option>
                    <option>
                      Smart cities
                    </option>
                    <option>
                      Energy
                    </option>
                    <option>
                      Several of these
                    </option>
                  </select>
                </div>
                <div className='field'>
                  <label htmlFor='pt'>
                    Tier you are considering
                  </label>
                  <select className='select' id='pt' name='tier'>
                    <option>
                      Not sure yet — advise me
                    </option>
                    <option>
                      Supporting
                    </option>
                    <option>
                      Silver
                    </option>
                    <option>
                      Gold
                    </option>
                    <option>
                      Presenting
                    </option>
                    <option>
                      Annual programme
                    </option>
                  </select>
                </div>
              </div>
              <div className='field mt-5'>
                <label htmlFor='pm'>
                  What are you hoping to get out of it?
                </label>
                <textarea className='textarea' id='pm' name='message' placeholder='The audience you want, the outcome you are measured on, and any events you already have in mind.'></textarea>
              </div>
              <button className='btn btn-primary btn-lg mt-6' type='submit'>
                Send enquiry{' '}
                <svg className='btn__icon' width='15' height='15' aria-hidden='true'>
                  <use href='#i-arrow' />
                </svg>
              </button>
            </form>
          </div>
        </div>
      </section>
    </>
  );
}
